### ISSUE TITLE
crash on infinite loop processing a call

### ISSUE THREAD

**Issue by linuxmaniac** [kamailio/kamailio#1263]
### Description

config was wrongly sending the call to a not properly constructed destination and the loop end was not properly detected so a infinite loop was created.

Anyhow, kamailio process should not crash.

#### Debugging Data

```
(gdb) bt
#0  0x0000000000568783 in rval_get_tmp_str (h=0x0, msg=0x0, tmpv=0x0, rv=0x0, cache=0x0, tmp_cache=0x0) at core/rvalue.c:1098
#1  0x0000000000569889 in rval_convert (h=0x7fff558296a0, msg=0x7efefebd5fb8, type=RV_STR, v=0x7eff0f922c70, c=0x0) at core/rvalue.c:1308
#2  0x000000000056b3a0 in rval_str_add2 (h=0x7fff558296a0, msg=0x7efefebd5fb8, l=0x7eff0f922540, c1=0x0, r=0x7eff0f922c70, c2=0x0) at core/rvalue.c:1634
#3  0x000000000057211e in rval_expr_eval (h=0x7fff558296a0, msg=0x7efefebd5fb8, rve=0x7eff0f923398) at core/rvalue.c:2462
#4  0x00000000005717ad in rval_expr_eval (h=0x7fff558296a0, msg=0x7efefebd5fb8, rve=0x7eff0f9241f8) at core/rvalue.c:2446
#5  0x00000000005717ad in rval_expr_eval (h=0x7fff558296a0, msg=0x7efefebd5fb8, rve=0x7eff0f925058) at core/rvalue.c:2446
#6  0x00000000005717ad in rval_expr_eval (h=0x7fff558296a0, msg=0x7efefebd5fb8, rve=0x7eff0f925f28) at core/rvalue.c:2446
#7  0x00000000004cb551 in lval_assign (h=0x7fff558296a0, msg=0x7efefebd5fb8, lv=0x7eff0f9223d8, rve=0x7eff0f925f28) at core/lvalue.c:384
#8  0x000000000043e38a in do_action (h=0x7fff558296a0, a=0x7eff0f926658, msg=0x7efefebd5fb8) at core/action.c:1430
#9  0x000000000043fe83 in run_actions (h=0x7fff558296a0, a=0x7eff0f917968, msg=0x7efefebd5fb8) at core/action.c:1552
#10 0x000000000042f7a1 in do_action (h=0x7fff558296a0, a=0x7eff0f8f9b18, msg=0x7efefebd5fb8) at core/action.c:678
#11 0x000000000043fe83 in run_actions (h=0x7fff558296a0, a=0x7eff0f8f9b18, msg=0x7efefebd5fb8) at core/action.c:1552
#12 0x0000000000440563 in run_actions_safe (h=0x7fff5582aee0, a=0x7eff0f8f9b18, msg=0x7efefebd5fb8) at core/action.c:1620
#13 0x000000000056794f in rval_get_int (h=0x7fff5582aee0, msg=0x7efefebd5fb8, i=0x7fff55829a84, rv=0x7eff0f8f9c70, cache=0x0) at core/rvalue.c:912
#14 0x000000000056bfc9 in rval_expr_eval_int (h=0x7fff5582aee0, msg=0x7efefebd5fb8, res=0x7fff55829a84, rve=0x7eff0f8f9c68) at core/rvalue.c:1906
#15 0x000000000042b45a in do_action (h=0x7fff5582aee0, a=0x7eff0f8fa398, msg=0x7efefebd5fb8) at core/action.c:345
#16 0x000000000043fe83 in run_actions (h=0x7fff5582aee0, a=0x7eff0f8fa398, msg=0x7efefebd5fb8) at core/action.c:1552
#17 0x0000000000432f47 in do_action (h=0x7fff5582aee0, a=0x7eff0f8fa4e8, msg=0x7efefebd5fb8) at core/action.c:1045
#18 0x000000000043fe83 in run_actions (h=0x7fff5582aee0, a=0x7eff0f8f15c0, msg=0x7efefebd5fb8) at core/action.c:1552
#19 0x000000000042f7a1 in do_action (h=0x7fff5582aee0, a=0x7eff0f926bb0, msg=0x7efefebd5fb8) at core/action.c:678
#20 0x000000000043fe83 in run_actions (h=0x7fff5582aee0, a=0x7eff0f926bb0, msg=0x7efefebd5fb8) at core/action.c:1552
#21 0x0000000000440563 in run_actions_safe (h=0x7fff5582c040, a=0x7eff0f926bb0, msg=0x7efefebd5fb8) at core/action.c:1620
[...]
(gdb) f 8
#8  0x000000000043e38a in do_action (h=0x7fff558296a0, a=0x7eff0f926658, msg=0x7efefebd5fb8) at core/action.c:1430
1430				v=lval_assign(h, msg, (struct lvalue*)a->val[0].u.data,
(gdb) p (struct lvalue*)a->val[0].u.data
$1 = (struct lvalue *) 0x7eff0f9223d8
(gdb) p *(struct lvalue*)a->val[0].u.data
$2 = {type = LV_PVAR, lv = {pvs = 0x7eff0f7dcf38, avps = {type = 259903288, name = {n = 0, s = {s = 0x0, len = 0}, re = 0x0}, index = 0}}}
(gdb) f 7
#7  0x00000000004cb551 in lval_assign (h=0x7fff558296a0, msg=0x7efefebd5fb8, lv=0x7eff0f9223d8, rve=0x7eff0f925f28) at core/lvalue.c:384
384		rv=rval_expr_eval(h, msg, rve);
(gdb) p *rve
$3 = {op = RVE_CONCAT_OP, left = {rve = 0x7eff0f925058, rval = {type = 261247064, refcnt = 32511, v = {p = 0x0, l = 0, s = {s = 0x0, len = 0}, avps = {type = 0, name = {n = 0, s = {s = 0x0, len = 0}, re = 0x0}, index = 0}, sel = {f = {0x0, 0x0, 0x0, 0x0}, param_offset = {0, 0, 0, 
            0, 0}, params = {{type = SEL_PARAM_INT, v = {i = 0, s = {s = 0x0, len = 0}, p = 0x0}} <repeats 32 times>}, n = 0}, pvs = {type = PVT_NONE, getf = 0x0, setf = 0x0, pvp = {pvn = {type = 0, nfree = 0x0, u = {isname = {type = 0, name = {n = 0, s = {s = 0x0, len = 0}, 
                    re = 0x0}}, dname = 0x0}}, pvi = {type = 0, u = {ival = 0, dval = 0x0}}}, trans = 0x0}, action = 0x0, bexpr = 0x0, re = {s = {s = 0x0, len = 0}, regex = 0x0}}, bsize = 0, flags = 0, buf = ""}}, right = {rve = 0x7eff0f925788, rval = {type = 261248904, 
      refcnt = 32511, v = {p = 0x0, l = 0, s = {s = 0x0, len = 0}, avps = {type = 0, name = {n = 0, s = {s = 0x0, len = 0}, re = 0x0}, index = 0}, sel = {f = {0x0, 0x0, 0x0, 0x0}, param_offset = {0, 0, 0, 0, 0}, params = {{type = SEL_PARAM_INT, v = {i = 0, s = {s = 0x0, len = 0}, 
                p = 0x0}} <repeats 32 times>}, n = 0}, pvs = {type = PVT_NONE, getf = 0x0, setf = 0x0, pvp = {pvn = {type = 0, nfree = 0x0, u = {isname = {type = 0, name = {n = 0, s = {s = 0x0, len = 0}, re = 0x0}}, dname = 0x0}}, pvi = {type = 0, u = {ival = 0, dval = 0x0}}}, 
          trans = 0x0}, action = 0x0, bexpr = 0x0, re = {s = {s = 0x0, len = 0}, regex = 0x0}}, bsize = 0, flags = 0, buf = ""}}, fpos = {s_line = 1144, e_line = 1144, s_col = 11, e_col = 62, fname = 0x7fff56026e01 "/etc/kamailio/kamailio.cfg", 
    rname = 0x7eff0f915db0 "SEND_TO_NEXT_DISPATCH"}}
(gdb) f 6
#6  0x00000000005717ad in rval_expr_eval (h=0x7fff558296a0, msg=0x7efefebd5fb8, rve=0x7eff0f925f28) at core/rvalue.c:2446
2446				rv1=rval_expr_eval(h, msg, rve->left.rve);
(gdb) p rve->left.rve
$4 = (struct rval_expr *) 0x7eff0f925058
(gdb) p *rve->left.rve
$5 = {op = RVE_CONCAT_OP, left = {rve = 0x7eff0f9241f8, rval = {type = 261243384, refcnt = 32511, v = {p = 0x0, l = 0, s = {s = 0x0, len = 0}, avps = {type = 0, name = {n = 0, s = {s = 0x0, len = 0}, re = 0x0}, index = 0}, sel = {f = {0x0, 0x0, 0x0, 0x0}, param_offset = {0, 0, 0, 
            0, 0}, params = {{type = SEL_PARAM_INT, v = {i = 0, s = {s = 0x0, len = 0}, p = 0x0}} <repeats 32 times>}, n = 0}, pvs = {type = PVT_NONE, getf = 0x0, setf = 0x0, pvp = {pvn = {type = 0, nfree = 0x0, u = {isname = {type = 0, name = {n = 0, s = {s = 0x0, len = 0}, 
                    re = 0x0}}, dname = 0x0}}, pvi = {type = 0, u = {ival = 0, dval = 0x0}}}, trans = 0x0}, action = 0x0, bexpr = 0x0, re = {s = {s = 0x0, len = 0}, regex = 0x0}}, bsize = 0, flags = 0, buf = ""}}, right = {rve = 0x7eff0f924928, rval = {type = 261245224, 
      refcnt = 32511, v = {p = 0x0, l = 0, s = {s = 0x0, len = 0}, avps = {type = 0, name = {n = 0, s = {s = 0x0, len = 0}, re = 0x0}, index = 0}, sel = {f = {0x0, 0x0, 0x0, 0x0}, param_offset = {0, 0, 0, 0, 0}, params = {{type = SEL_PARAM_INT, v = {i = 0, s = {s = 0x0, len = 0}, 
                p = 0x0}} <repeats 32 times>}, n = 0}, pvs = {type = PVT_NONE, getf = 0x0, setf = 0x0, pvp = {pvn = {type = 0, nfree = 0x0, u = {isname = {type = 0, name = {n = 0, s = {s = 0x0, len = 0}, re = 0x0}}, dname = 0x0}}, pvi = {type = 0, u = {ival = 0, dval = 0x0}}}, 
          trans = 0x0}, action = 0x0, bexpr = 0x0, re = {s = {s = 0x0, len = 0}, regex = 0x0}}, bsize = 0, flags = 0, buf = ""}}, fpos = {s_line = 1144, e_line = 1144, s_col = 11, e_col = 52, fname = 0x7fff56026e01 "/etc/kamailio/kamailio.cfg", 
    rname = 0x7eff0f915db0 "SEND_TO_NEXT_DISPATCH"}}
(gdb) f 5
#5  0x00000000005717ad in rval_expr_eval (h=0x7fff558296a0, msg=0x7efefebd5fb8, rve=0x7eff0f925058) at core/rvalue.c:2446
2446				rv1=rval_expr_eval(h, msg, rve->left.rve);
(gdb) p rve->left.rve
$6 = (struct rval_expr *) 0x7eff0f9241f8
(gdb) p *rve->left.rve
$7 = {op = RVE_CONCAT_OP, left = {rve = 0x7eff0f923398, rval = {type = 261239704, refcnt = 32511, v = {p = 0x0, l = 0, s = {s = 0x0, len = 0}, avps = {type = 0, name = {n = 0, s = {s = 0x0, len = 0}, re = 0x0}, index = 0}, sel = {f = {0x0, 0x0, 0x0, 0x0}, param_offset = {0, 0, 0, 
            0, 0}, params = {{type = SEL_PARAM_INT, v = {i = 0, s = {s = 0x0, len = 0}, p = 0x0}} <repeats 32 times>}, n = 0}, pvs = {type = PVT_NONE, getf = 0x0, setf = 0x0, pvp = {pvn = {type = 0, nfree = 0x0, u = {isname = {type = 0, name = {n = 0, s = {s = 0x0, len = 0}, 
                    re = 0x0}}, dname = 0x0}}, pvi = {type = 0, u = {ival = 0, dval = 0x0}}}, trans = 0x0}, action = 0x0, bexpr = 0x0, re = {s = {s = 0x0, len = 0}, regex = 0x0}}, bsize = 0, flags = 0, buf = ""}}, right = {rve = 0x7eff0f923ac8, rval = {type = 261241544, 
      refcnt = 32511, v = {p = 0x0, l = 0, s = {s = 0x0, len = 0}, avps = {type = 0, name = {n = 0, s = {s = 0x0, len = 0}, re = 0x0}, index = 0}, sel = {f = {0x0, 0x0, 0x0, 0x0}, param_offset = {0, 0, 0, 0, 0}, params = {{type = SEL_PARAM_INT, v = {i = 0, s = {s = 0x0, len = 0}, 
                p = 0x0}} <repeats 32 times>}, n = 0}, pvs = {type = PVT_NONE, getf = 0x0, setf = 0x0, pvp = {pvn = {type = 0, nfree = 0x0, u = {isname = {type = 0, name = {n = 0, s = {s = 0x0, len = 0}, re = 0x0}}, dname = 0x0}}, pvi = {type = 0, u = {ival = 0, dval = 0x0}}}, 
          trans = 0x0}, action = 0x0, bexpr = 0x0, re = {s = {s = 0x0, len = 0}, regex = 0x0}}, bsize = 0, flags = 0, buf = ""}}, fpos = {s_line = 1144, e_line = 1144, s_col = 11, e_col = 28, fname = 0x7fff56026e01 "/etc/kamailio/kamailio.cfg", 
    rname = 0x7eff0f915db0 "SEND_TO_NEXT_DISPATCH"}}
(gdb) f 4
#4  0x00000000005717ad in rval_expr_eval (h=0x7fff558296a0, msg=0x7efefebd5fb8, rve=0x7eff0f9241f8) at core/rvalue.c:2446
2446				rv1=rval_expr_eval(h, msg, rve->left.rve);
(gdb) p rve->left.rve
$8 = (struct rval_expr *) 0x7eff0f923398
(gdb) p *rve->left.rve
$9 = {op = RVE_CONCAT_OP, left = {rve = 0x7eff0f922538, rval = {type = 261236024, refcnt = 32511, v = {p = 0x0, l = 0, s = {s = 0x0, len = 0}, avps = {type = 0, name = {n = 0, s = {s = 0x0, len = 0}, re = 0x0}, index = 0}, sel = {f = {0x0, 0x0, 0x0, 0x0}, param_offset = {0, 0, 0, 
            0, 0}, params = {{type = SEL_PARAM_INT, v = {i = 0, s = {s = 0x0, len = 0}, p = 0x0}} <repeats 32 times>}, n = 0}, pvs = {type = PVT_NONE, getf = 0x0, setf = 0x0, pvp = {pvn = {type = 0, nfree = 0x0, u = {isname = {type = 0, name = {n = 0, s = {s = 0x0, len = 0}, 
                    re = 0x0}}, dname = 0x0}}, pvi = {type = 0, u = {ival = 0, dval = 0x0}}}, trans = 0x0}, action = 0x0, bexpr = 0x0, re = {s = {s = 0x0, len = 0}, regex = 0x0}}, bsize = 0, flags = 0, buf = ""}}, right = {rve = 0x7eff0f922c68, rval = {type = 261237864, 
      refcnt = 32511, v = {p = 0x0, l = 0, s = {s = 0x0, len = 0}, avps = {type = 0, name = {n = 0, s = {s = 0x0, len = 0}, re = 0x0}, index = 0}, sel = {f = {0x0, 0x0, 0x0, 0x0}, param_offset = {0, 0, 0, 0, 0}, params = {{type = SEL_PARAM_INT, v = {i = 0, s = {s = 0x0, len = 0}, 
                p = 0x0}} <repeats 32 times>}, n = 0}, pvs = {type = PVT_NONE, getf = 0x0, setf = 0x0, pvp = {pvn = {type = 0, nfree = 0x0, u = {isname = {type = 0, name = {n = 0, s = {s = 0x0, len = 0}, re = 0x0}}, dname = 0x0}}, pvi = {type = 0, u = {ival = 0, dval = 0x0}}}, 
          trans = 0x0}, action = 0x0, bexpr = 0x0, re = {s = {s = 0x0, len = 0}, regex = 0x0}}, bsize = 0, flags = 0, buf = ""}}, fpos = {s_line = 1144, e_line = 1144, s_col = 11, e_col = 22, fname = 0x7fff56026e01 "/etc/kamailio/kamailio.cfg", 
    rname = 0x7eff0f915db0 "SEND_TO_NEXT_DISPATCH"}}
(gdb) f 3
#3  0x000000000057211e in rval_expr_eval (h=0x7fff558296a0, msg=0x7efefebd5fb8, rve=0x7eff0f923398) at core/rvalue.c:2462
2462				ret=rval_str_add2(h, msg, rv1, 0, rv2, 0);
(gdb) p r1 r2
No symbol "r1" in current context.
(gdb) p rv1
$10 = (struct rvalue *) 0x7eff0f922540
(gdb) p rv2
$11 = (struct rvalue *) 0x7eff0f922c70
(gdb) p *rv1
$12 = {type = RV_STR, refcnt = 3, v = {p = 0x7eff0f921e78, l = 139633942994552, s = {s = 0x7eff0f921e78 "sip:", len = 4}, avps = {type = 261234296, name = {n = 4, s = {s = 0x7eff00000004 "", len = 147196536}, re = 0x7eff00000004}, index = 1}, sel = {f = {0x7eff0f921e78, 
        0x7eff00000004, 0x7eff08c60a78 <pv_set_scriptvar>, 0x1}, param_offset = {0, 90, 7861601, 0, 261235616}, params = {{type = 258031632, v = {i = 0, s = {s = 0x0, len = 0}, p = 0x0}}, {type = 261235616, v = {i = 258031632, s = {s = 0x7eff0f614010 "\001", len = 0}, 
            p = 0x7eff0f614010}}, {type = 8108800, v = {i = 258032704, s = {s = 0x7eff0f614440 "", len = 258032704}, p = 0x7eff0f614440}}, {type = 1442987344, v = {i = 6691748, s = {s = 0x661ba4 <qm_free+6132> "H\201\304", <incomplete sequence \330>, len = 0}, 
            p = 0x661ba4 <qm_free+6132>}}, {type = 261233544, v = {i = 258031632, s = {s = 0x160f614010 <error: Cannot access memory at address 0x160f614010>, len = 1442987176}, p = 0x160f614010}}, {type = 6676612, v = {i = 261234240, s = {s = 0x7eff0f921e40 "\b", 
              len = 258031632}, p = 0x7eff0f921e40}}, {type = 1442987248, v = {i = 6682339, s = {s = 0x9f0065f6e3 <error: Cannot access memory at address 0x9f0065f6e3>, len = 258049504}, p = 0x9f0065f6e3}}, {type = 258049504, v = {i = 1442987280, s = {
              s = 0x7fff56023d10 "\260's\001", len = 6682339}, p = 0x7fff56023d10}}, {type = 8389724, v = {i = 8112983, s = {s = 0x7bcb57 "fragm. from qm_malloc", len = 8389724}, p = 0x7bcb57}}, {type = 128, v = {i = 261234008, s = {s = 0x7eff0f921d58 "\200", len = 258031632}, 
            p = 0x7eff0f921d58}}, {type = 23734457, v = {i = 0, s = {s = 0x0, len = 8108800}, p = 0x0}}, {type = 261234240, v = {i = 23734457, s = {s = 0x16a28b9 "ip:", len = 1442987536}, p = 0x16a28b9}}, {type = 6684728, v = {i = 8388886, s = {s = 0x800116 "core", 
              len = 23734452}, p = 0x800116}}, {type = 1442987568, v = {i = 6684728, s = {s = 0x660038 <qm_malloc+2370> "H\213E\310H\203\300\070\351Y\003", len = 8388886}, p = 0x660038 <qm_malloc+2370>}}, {type = 258056000, v = {i = 1442987616, s = {s = 0x7fff56023e60 "\t", 
              len = 6691748}, p = 0x7fff56023e60}}, {type = 7844384, v = {i = 5664136, s = {s = 0x7600566d88 <error: Cannot access memory at address 0x7600566d88>, len = 7860583}, p = 0x7600566d88}}, {type = 7844389, v = {i = 8388886, s = {s = 0x800116 "core", len = 258031632}, 
            p = 0x800116}}, {type = 8402319, v = {i = 8389724, s = {s = 0x80045c "core: core/cfg.lex", len = 128}, p = 0x80045c}}, {type = 258031632, v = {i = 8402319, s = {s = 0x80358f <__FUNCTION__.7705> "addstr", len = 8389724}, p = 0x80358f <__FUNCTION__.7705>}}, {
          type = SEL_PARAM_STR, v = {i = 258031632, s = {s = 0x7eff0f614010 "\001", len = 258031632}, p = 0x7eff0f614010}}, {type = 261234008, v = {i = 1, s = {s = 0x7eff00000001 "", len = 23734457}, p = 0x7eff00000001}}, {type = 374, v = {i = 23734456, s = {s = 0x16a28b8 "sip:", 
              len = 8}, p = 0x16a28b8}}, {type = SEL_PARAM_INT, v = {i = 1442987680, s = {s = 0x7fff56023ea0 "\210\037", len = 7461677}, p = 0x7fff56023ea0}}, {type = 1442987824, v = {i = 8463786, s = {s = 0xa45008125aa <error: Cannot access memory at address 0xa45008125aa>, 
              len = 8112983}, p = 0xa45008125aa}}, {type = 7461677, v = {i = 1442987700, s = {s = 0x7fff56023eb4 "\376~", len = 11420944}, p = 0x7fff56023eb4}}, {type = 261235672, v = {i = 0, s = {s = 0x0, len = 23734460}, p = 0x0}}, {type = 11420944, v = {i = 258032704, s = {
              s = 0x7eff0f614440 "", len = 23734460}, p = 0x7eff0f614440}}, {type = 374, v = {i = 23734459, s = {s = 0x16a28bb ":", len = 11420972}, p = 0x16a28bb}}, {type = 23734462, v = {i = 377, s = {s = 0x179 <error: Cannot access memory at address 0x179>, len = 23734462}, 
            p = 0x179}}, {type = SEL_PARAM_STR, v = {i = 0, s = {s = 0x0, len = 1442987904}, p = 0x0}}, {type = 7446070, v = {i = 261227880, s = {s = 0x7eff0f920568 "\"", len = 261235672}, p = 0x7eff0f920568}}, {type = SEL_PARAM_INT, v = {i = 258384760, s = {
              s = 0x7eff0f66a378 "blue.foeedc.proxy.staging.voxivo.com", len = 0}, p = 0x7eff0f66a378}}}, n = 0}, pvs = {type = 261234296, getf = 0x7eff00000004, setf = 0x7eff08c60a78 <pv_set_scriptvar>, pvp = {pvn = {type = 1, nfree = 0x5a00000000, u = {isname = {type = 7861601, 
              name = {n = 261235616, s = {s = 0x7eff0f9223a0 "H", len = 258031632}, re = 0x7eff0f9223a0}}, dname = 0x77f561}}, pvi = {type = 0, u = {ival = 0, dval = 0x0}}}, trans = 0x7eff0f9223a0}, action = 0x7eff0f921e78, bexpr = 0x7eff0f921e78, re = {s = {
        s = 0x7eff0f921e78 "sip:", len = 4}, regex = 0x7eff08c60a78 <pv_set_scriptvar>}}, bsize = 0, flags = 1, buf = ""}
(gdb) p *rv2
$13 = {type = RV_PVAR, refcnt = 2, v = {p = 0x7, l = 7, s = {s = 0x7 <error: Cannot access memory at address 0x7>, len = 147123646}, avps = {type = 7, name = {n = 147123646, s = {
          s = 0x7eff08c4edbe <pv_get_ruri_attr> "UH\211\345AWAVAUATSH\203\354HH\211}\270H\211u\260H\211U\250H\203}\270", len = 147203592}, re = 0x7eff08c4edbe <pv_get_ruri_attr>}, index = 0}, sel = {f = {0x7, 0x7eff08c4edbe <pv_get_ruri_attr>, 0x7eff08c62608 <pv_set_ruri_user>, 
        0x0}, param_offset = {0, 0, 0, 0, 1}, params = {{type = SEL_PARAM_INT, v = {i = 0, s = {s = 0x0, len = 0}, p = 0x0}}, {type = SEL_PARAM_INT, v = {i = 258031632, s = {s = 0x7eff0f614010 "\001", len = 0}, p = 0x7eff0f614010}}, {type = 8108800, v = {i = 258032704, s = {
              s = 0x7eff0f614440 "", len = 258032704}, p = 0x7eff0f614440}}, {type = 1442987344, v = {i = 6691748, s = {s = 0x661ba4 <qm_free+6132> "H\201\304", <incomplete sequence \330>, len = 0}, p = 0x661ba4 <qm_free+6132>}}, {type = 261233544, v = {i = 258031632, s = {
              s = 0x160f614010 <error: Cannot access memory at address 0x160f614010>, len = 1442987176}, p = 0x160f614010}}, {type = 6676612, v = {i = 261234240, s = {s = 0x7eff0f921e40 "\b", len = 258031632}, p = 0x7eff0f921e40}}, {type = 1442987248, v = {i = 6682339, s = {
              s = 0x9f0065f6e3 <error: Cannot access memory at address 0x9f0065f6e3>, len = 261234584}, p = 0x9f0065f6e3}}, {type = 258031632, v = {i = 1442987280, s = {s = 0x7fff56023d10 "\260's\001", len = 6682339}, p = 0x7fff56023d10}}, {type = 258044688, v = {i = 258044688, 
            s = {s = 0x7eff0f617310 "", len = 1442987312}, p = 0x7eff0f617310}}, {type = 6682339, v = {i = 8389724, s = {s = 0x5670080045c <error: Cannot access memory at address 0x5670080045c>, len = 8112983}, p = 0x5670080045c}}, {type = 8389724, v = {i = 128, s = {
              s = 0x80 <error: Cannot access memory at address 0x80>, len = 261234352}, p = 0x80}}, {type = 258031632, v = {i = 23734467, s = {s = 0x16a28c3 " + \"@", len = 0}, p = 0x16a28c3}}, {type = 8108800, v = {i = 261234584, s = {s = 0x7eff0f921f98 "(", len = 23734467}, 
            p = 0x7eff0f921f98}}, {type = 1442987568, v = {i = 6684728, s = {s = 0x660038 <qm_malloc+2370> "H\213E\310H\203\300\070\351Y\003", len = 8388886}, p = 0x660038 <qm_malloc+2370>}}, {type = 258056000, v = {i = 1442987616, s = {s = 0x7fff56023e60 "\t", len = 6691748}, 
            p = 0x7fff56023e60}}, {type = 7844384, v = {i = 5664136, s = {s = 0x7600566d88 <error: Cannot access memory at address 0x7600566d88>, len = 7860583}, p = 0x7600566d88}}, {type = 7844389, v = {i = 8388886, s = {s = 0x800116 "core", len = 258031632}, p = 0x800116}}, {
          type = 8402319, v = {i = 8389724, s = {s = 0x80045c "core: core/cfg.lex", len = 8388886}, p = 0x80045c}}, {type = 258031632, v = {i = 8402319, s = {s = 0x80358f <__FUNCTION__.7705> "addstr", len = 8389724}, p = 0x80358f <__FUNCTION__.7705>}}, {type = 128, v = {
            i = 258031632, s = {s = 0x7eff0f614010 "\001", len = 258031632}, p = 0x7eff0f614010}}, {type = 261234008, v = {i = 1, s = {s = 0x7eff00000001 "", len = 261234728}, p = 0x7eff00000001}}, {type = 258031632, v = {i = 261234352, s = {s = 0x7eff0f921eb0 "\200", len = 8}, 
            p = 0x7eff0f921eb0}}, {type = 258042672, v = {i = 258042672, s = {s = 0x7eff0f616b30 "", len = 1442987648}, p = 0x7eff0f616b30}}, {type = 6682339, v = {i = 8463786, s = {s = 0xa45008125aa <error: Cannot access memory at address 0xa45008125aa>, len = 8112983}, 
            p = 0xa45008125aa}}, {type = 261234408, v = {i = 40, s = {s = 0x400000028 <error: Cannot access memory at address 0x400000028>, len = 7783792}, p = 0x400000028}}, {type = 261234640, v = {i = 0, s = {s = 0x0, len = 1442987776}, p = 0x0}}, {type = 5313571, v = {
            i = 261234728, s = {s = 0x7eff0f922028 "\200", len = 261235672}, p = 0x7eff0f922028}}, {type = 1442987904, v = {i = 6684728, s = {s = 0x660038 <qm_malloc+2370> "H\213E\310H\203\300\070\351Y\003", len = 8402432}, p = 0x660038 <qm_malloc+2370>}}, {type = 23734467, v = {
            i = 326, s = {s = 0x146 <error: Cannot access memory at address 0x146>, len = 1442987840}, p = 0x146}}, {type = SEL_PARAM_DIV, v = {i = 3, s = {s = 0x21014500000003 <error: Cannot access memory at address 0x21014500000003>, len = 0}, p = 0x21014500000003}}, {
          type = 259906520, v = {i = 261227880, s = {s = 0x7eff0f920568 "\"", len = 261234640}, p = 0x7eff0f920568}}, {type = SEL_PARAM_INT, v = {i = 258384760, s = {s = 0x7eff0f66a378 "blue.foeedc.proxy.staging.voxivo.com", len = 0}, p = 0x7eff0f66a378}}}, n = 0}, pvs = {
      type = PVT_RURI_USERNAME, getf = 0x7eff08c4edbe <pv_get_ruri_attr>, setf = 0x7eff08c62608 <pv_set_ruri_user>, pvp = {pvn = {type = 0, nfree = 0x0, u = {isname = {type = 0, name = {n = 1, s = {s = 0x1 <error: Cannot access memory at address 0x1>, len = 0}, re = 0x1}}, 
            dname = 0x0}}, pvi = {type = 0, u = {ival = 0, dval = 0x0}}}, trans = 0x0}, action = 0x7, bexpr = 0x7, re = {s = {s = 0x7 <error: Cannot access memory at address 0x7>, len = 147123646}, regex = 0x7eff08c62608 <pv_set_ruri_user>}}, bsize = 0, flags = 0, buf = ""}
(gdb)
(gdb) f 2
#2  0x000000000056b3a0 in rval_str_add2 (h=0x7fff558296a0, msg=0x7efefebd5fb8, l=0x7eff0f922540, c1=0x0, r=0x7eff0f922c70, c2=0x0) at core/rvalue.c:1634
1634		if ((rv2=rval_convert(h, msg, RV_STR, r, c2))==0)
(gdb) f 1
#1  0x0000000000569889 in rval_convert (h=0x7fff558296a0, msg=0x7efefebd5fb8, type=RV_STR, v=0x7eff0f922c70, c=0x0) at core/rvalue.c:1308
1308				if (unlikely(rval_get_tmp_str(h, msg, &tmp, v, c, &tmp_cache) < 0))
(gdb) f 0
#0  0x0000000000568783 in rval_get_tmp_str (h=0x0, msg=0x0, tmpv=0x0, rv=0x0, cache=0x0, tmp_cache=0x0) at core/rvalue.c:1098
1098	{
```

**Comment by miconda** [comment]
Was the patch referred above the fix for this issue? If yes, should this be closed?

**Comment by miconda** [comment]
Should it be backported?

**Comment by linuxmaniac** [comment]
done, thanks
