### ISSUE TITLE
Core crashed, EOF on 23

### ISSUE THREAD

**Issue by Jaykah** [kamailio/kamailio#158]
```
kamailio 4.3.0-pre0 (x86_64/linux) e1d68c
flags: STATS: Off, USE_TCP, USE_TLS, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, F_MALLOC, DBG_F_MALLOC, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: e1d68c
```

Hi,

Today everything was business as usual, when this happened:
```
May 13 03:40:32 Kamailio2 kamailio[7104]: CRITICAL: <core> [pass_fd.c:275]: receive_fd(): EOF on 23
May 13 03:40:32 Kamailio2 kamailio[7064]: ALERT: <core> [main.c:728]: handle_sigs(): child process 7066 exited by a signal 11
May 13 03:40:32 Kamailio2 kamailio[7064]: ALERT: <core> [main.c:731]: handle_sigs(): core was generated
May 13 03:40:32 Kamailio2 kamailio[7064]: INFO: <core> [main.c:743]: handle_sigs(): terminating due to SIGCHLD
May 13 03:40:32 Kamailio2 kamailio[7068]: INFO: <core> [main.c:794]: sig_usr(): signal 15 received
```

Needless to say, Kamailio crashed (thankfully after hours). No more related logs, unfortunately. 

Was wondering if you can tell anything just by the excerpt above.

Thanks.

**Comment by miconda** [comment]
You have to locate the core file, it should be in / or in the folder the OS was configured to write core dumps (usually a file named core or core.7066 or something starting with core). Then get the backtrace from it with gdb:

```
gdb /path/to/kamailio /path/to/corefile
bt full
```

Add the output to this issue.

You are also running the master branch with version 4.3.0-pre0, at this moment the latest is 4.3.0-pre1, which includes some more fixes. Might be good to upgrade. Be aware that you may need to upgrade database schema, see:

  * http://www.kamailio.org/wiki/install/upgrade/stable-to-devel

**Comment by miconda** [comment]
Going to close the issue as it was about devel version, testing hasn't reported any similar issue and no follow up was made in three weeks. If there is anything new related to this issue, re-open.

**Comment by camilleoudot** [comment]
Hi,
we had this same kind of crash last night:

```
kamailio[19419]: ERROR: <core> [io_wait.h:394]: io_watch_add(): trying to overwrite entry 564 watched for 1 in the hash(564, 2, 0x7fc348f5b960) with (564, 2, 0x7fc34aca4420)
kamailio[19419]: CRITICAL: <core> [tcp_main.c:4049]: handle_new_connect(): failed to add new socket to the fd list
kamailio[19419]: CRITICAL: <core> [pass_fd.c:293]: receive_fd(): EOF on 125
kamailio[19324]: ALERT: <core> [main.c:784]: handle_sigs(): child process 19417 exited by a signal 11
kamailio[19324]: ALERT: <core> [main.c:787]: handle_sigs(): core was generated
```

We have the backtrace:

```
#0  0x0000000000566906 in local_timer_list_expire (l=0xa37f80 <tcp_reader_ltimer>, t=1559677467, h=0xa42138 <tcp_reader_ltimer+41400>) at local_timer.c:214
#1  0x0000000000566a60 in local_timer_expire (h=0xa37f80 <tcp_reader_ltimer>, t=1559677467) at local_timer.c:243
#2  0x0000000000566d0a in local_timer_run (lt=0xa37f80 <tcp_reader_ltimer>, saved_ticks=1559677469) at local_timer.c:266
#3  0x00000000005f94fe in tcp_reader_timer_run () at tcp_read.c:1713
#4  0x00000000005f986f in tcp_receive_loop (unix_sock=129) at tcp_read.c:1765
#5  0x00000000004e75d8 in tcp_init_children () at tcp_main.c:4880
#6  0x0000000000517828 in main_loop () at main.c:1714
#7  0x000000000051caec in main (argc=15, argv=0x7fff764de168) at main.c:2581
```
local_timer.c:214 corresponds to:

```
	while(h->next!=(struct timer_ln*)h){
		tl=h->next;
=>		_timer_rm_list(tl); /* detach */
			tl->next=tl->prev=0; /* debugging */
				/*FIXME: process tcpconn */
```

We are running kamailio 4.2.4 (with backports of tcpops module and ursloc's close_expired_tcp new feature)

Any idea?

**Comment by miconda** [comment]
Be sure you run 4.2 branch after the commit bf8be8c52039fc50dafd0c9c140c01ab84384977

**Comment by camilleoudot** [comment]
Thanks, we will update our kamailio to include it. We don't use tm suspend/continue on this particular box though.

**Comment by miconda** [comment]
Reopen if new details are collected.
