### ISSUE TITLE
Crash when disable_tcp=yes and defined tcp socket 

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#1845]
### Description

kamailio cannot start if `disable_tcp=yes` and defined tcp socket like
```
listen=tcp:0.0.0.0:5060
``` 

#### Reproduction
 Need to define `disable_tcp=yes and `listen=tcp:0.0.0.0:5060` in config file

#### Debugging Data
```
(gdb) bt full
#0  uac_init () at uac.c:96
        src = {{s = 0x7fa3982230a4 "Long live kamailio server", len = 25}, {s = 0x0, len = -198457925}, {s = 0x0, len = -1741379408}}
        si = 0x7fa398336828
        __func__ = "uac_init"
        __llevel = <optimized out>
#1  0x00007fa3981c6899 in mod_init () at tm.c:779
        __func__ = "mod_init"
#2  0x0000564bf414df8f in init_mod (m=0x7fa3983293e0) at core/sr_module.c:910
        __func__ = "init_mod"
#3  0x0000564bf414ddac in init_mod (m=0x7fa39832b1f8) at core/sr_module.c:907
        __func__ = "init_mod"
#4  0x0000564bf414ddac in init_mod (m=0x7fa39832b8b8) at core/sr_module.c:907
        __func__ = "init_mod"
#5  0x0000564bf414ddac in init_mod (m=0x7fa39832c4d0) at core/sr_module.c:907
        __func__ = "init_mod"
#6  0x0000564bf414ddac in init_mod (m=0x7fa398333ef0) at core/sr_module.c:907
        __func__ = "init_mod"
#7  0x0000564bf414ddac in init_mod (m=0x7fa398334468) at core/sr_module.c:907
        __func__ = "init_mod"
#8  0x0000564bf414ddac in init_mod (m=0x7fa398335478) at core/sr_module.c:907
        __func__ = "init_mod"
#9  0x0000564bf414ddac in init_mod (m=0x7fa398336008) at core/sr_module.c:907
        __func__ = "init_mod"
#10 0x0000564bf414f5b9 in init_modules () at core/sr_module.c:939
        t = <optimized out>
        i = <optimized out>
        __func__ = "init_modules"
#11 0x0000564bf40de4b2 in main (argc=<optimized out>, argv=<optimized out>) at main.c:2608
        cfg_stream = <optimized out>
        c = <optimized out>
        r = <optimized out>
        tmp = 0x18 <error: Cannot access memory at address 0x18>
        tmp_len = 24
        port = 0
        proto = 28653
        options = 0x564bf42ec29d ":f:cm:M:dVIhEeb:l:L:n:vKrRDTN:W:w:t:u:g:P:G:SQ:O:a:A:x:X:Y:"
        ret = -1
        seed = 2830532612
        rfd = <optimized out>
        debug_save = <optimized out>
        debug_flag = <optimized out>
        dont_fork_cnt = <optimized out>
        n_lst = <optimized out>
        p = <optimized out>
        st = {st_dev = 60, st_ino = 680219, st_nlink = 1, st_mode = 16877, st_uid = 100, st_gid = 0, __pad0 = 0, st_rdev = 0, st_size = 4096, st_blksize = 4096, st_blocks = 8, st_atim = {tv_sec = 1549678202, tv_nsec = 261414570}, st_mtim = {tv_sec = 1549678398, tv_nsec = 300838736}, st_ctim = {tv_sec = 1549678398, tv_nsec = 300838736}, __unused = {0, 0, 0}}
        __func__ = "main"
(gdb) info locals
src = {{s = 0x7fa3982230a4 "Long live kamailio server", len = 25}, {s = 0x0, len = -198457925}, {s = 0x0, len = -1741379408}}
si = 0x7fa398336828
__func__ = "uac_init"
__llevel = <optimized out>
(gdb) list
91	in uac.c
```

#### Log Messages

None

#### SIP Traffic

None

### Possible Solutions

Now known

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`
current master

```
/ # kamailio -v
version: kamailio 5.3.0-dev1 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled on 23:30:38 Jan  1 2019 with gcc 8.2.0
```

* **Operating System**:

```
/ # cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.8.0
PRETTY_NAME="Alpine Linux v3.8"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

**Comment by henningw** [comment]
This looks like the same issue reported some days ago. Can you please check f0290969fdcbbeed, it should be fixed there.

**Comment by sergey-safarov** [comment]
Yes, tested latest master
Issue is fixed.

**Comment by henningw** [comment]
Thank you for the confirmation.
