### ISSUE TITLE
python3 exception - tm.t_relay not return int

### ISSUE THREAD

**Issue by aztrock** [kamailio/kamailio#2366]
Extract from examples.

```
Jun 19 11:07:47 localhost kamailio[8645]:  5(8658) ERROR: app_python3 [python_support.c:156]: python_handle_exception(): apy_exec: ksr_request_route((null)): Unhandled exception in the Python code:
Jun 19 11:07:47 localhost kamailio[8645]: AttributeError: 'kamailio' object has no attribute 'ksr_onsend_route'
Jun 19 11:07:47 localhost kamailio[8645]: During handling of the above exception, another exception occurred:
Jun 19 11:07:47 localhost kamailio[8645]: Traceback (most recent call last):
Jun 19 11:07:47 localhost kamailio[8645]:   File "/etc/kamailio/kamailio.py", line 68, in ksr_request_route
Jun 19 11:07:47 localhost kamailio[8645]:     if self.ksr_route_withindlg(msg) ==- 255:
Jun 19 11:07:47 localhost kamailio[8645]:   File "/etc/kamailio/kamailio.py", line 202, in ksr_route_withindlg
Jun 19 11:07:47 localhost kamailio[8645]:     self.ksr_route_relay(msg)
Jun 19 11:07:47 localhost kamailio[8645]:   File "/etc/kamailio/kamailio.py", line 135, in ksr_route_relay
Jun 19 11:07:47 localhost kamailio[8645]:     if KSR.tm.t_relay():
Jun 19 11:07:47 localhost kamailio[8645]: SystemError: <built-in function t_relay> returned a result with an error set
Jun 19 11:07:47 localhost kamailio[8645]:  5(8658) DEBUG: app_python3 [apy_kemi.c:112]: sr_kemi_config_engine_python(): execution of route type 1 with no name returned -1
```

**Comment by miconda** [comment]
`KSR.tm.t_relay()` is returning int. The sample config has it like `if KSR.tm.t_relay() < 0:`, but I guess it should work evaluating an int anyhow in the if condition of python. Does it happen every time the script is executed? Do you get any other error messages before those pasted above, from the start of kamailio?

**Comment by miconda** [comment]
Any updates on this with requested details?

**Comment by miconda** [comment]
Closing, not reproducible. Reopen if new details can be provided.
