### ISSUE TITLE
core dump on avp_delete("*")

### ISSUE THREAD

**Issue by adubovikov** [kamailio/kamailio#239]
If I use avp_delete("*") kamailio crash. This issue effects on 4.1.x, 4.2.x 4.3.x.
```
#0  0x00007f0ff0590bfc in ops_delete_avp (msg=0x7f0ff386e330, ap=0x7f0ff380c800) at avpops_impl.c:794
        avp_list = 0x7f0fe65bb420
        avp = 0x7f0fe65bb420
        avp_next = 0x7f0fe65bb3a0
        name_type = 65
        avp_name = {n = -209757528, s = {s = 0x7f0ff37f5aa8 "\020", len = -255303345}, re = 0x7f0ff37f5aa8}
        n = 0
        __FUNCTION__ = "ops_delete_avp"
#1  0x00007f0ff0582d23 in w_delete_avps (msg=0x7f0ff386e330, param=0x7f0ff380c800 "", foo=0x0) at avpops.c:989
No locals.
#2  0x0000000000420654 in do_action (h=0x7fffc4c7ff30, a=0x7f0ff382eae8, msg=0x7f0ff386e330) at action.c:1059
        ret = -5
        v = -993531728
        dst = {send_sock = 0x7fffc4c7e960, to = {s = {sa_family = 38884, sa_data = "T\000\000\000\000\000\357\201\t'\000\000\000"}, sin = {sin_family = 38884, sin_port = 84, sin_addr = {s_addr = 0},
              sin_zero = "\357\201\t'\000\000\000"}, sin6 = {sin6_family = 38884, sin6_port = 84, sin6_flowinfo = 0, sin6_addr = {__in6_u = {__u6_addr8 = "\357\201\t'\000\000\000\000\300\207A\000\000\000\000", __u6_addr16 = {33263,
                    9993, 0, 0, 34752, 65, 0, 0}, __u6_addr32 = {654934511, 0, 4294592, 0}}}, sin6_scope_id = 3301435744}}, id = 32767, proto = 41 ')', send_flags = {f = 200 '\310', blst_imask = 84 'T'}}
        tmp = 0x7f0ff37f9270 "?|"
        new_uri = 0x7f0ff382cc40 "\a"
        end = 0x270981ef <Address 0x270981ef out of bounds>
        crt = 0x7f0ff380c370 " O\202\363\017\177"
        cmd = 0x7f0ff37e9b48
        len = 32527
        user = -209951136
        uri = {user = {s = 0x7fffc4c7e6cc "\001", len = 0}, passwd = {s = 0x7fffc4c7e6e0 "P\347\307\304\377\177", len = -260187898}, host = {s = 0x1000000 <Address 0x1000000 out of bounds>, len = -993531336}, port = {
            s = 0x7f0ff382cc60 "\001", len = -209263824}, params = {s = 0x7f0ff35b68c0 "db_mysql_get_columns", len = -993532032}, sip_params = {s = 0x7f0ff37f8218 "X\207\177\363\017\177", len = 11038340}, headers = {
            s = 0x7fffc4c7e750 "@ӂ\363\017\177", len = 5213356}, port_no = 23208, proto = 62335, type = 8, flags = 3301435264, transport = {s = 0x7fffc4c7e800 "`\351\307\304\377\177", len = 5527732}, ttl = {
            s = 0x920a0 <Address 0x920a0 out of bounds>, len = -993531336}, user_param = {s = 0x7f0ff382cc48 "\017", len = -209263824}, maddr = {s = 0xd <Address 0xd out of bounds>, len = 16777312}, method = {
            s = 0x7fffc4c7e770 "@̂\363\017\177", len = 0}, lr = {s = 0x7f0ff382d340 "\001", len = -993531276}, r2 = {s = 0x7f0ff386e330 "\001", len = -993525968}, gr = {s = 0x7f0ff382cc40 "\a", len = -993531272}, transport_val = {
            s = 0x7f0ff386e330 "\001", len = -993525968}, ttl_val = {s = 0x7f0ff386e330 "\001", len = -993525968}, user_param_val = {s = 0xb0f48 <Address 0xb0f48 out of bounds>, len = 8}, maddr_val = {
            s = 0xe <Address 0xe out of bounds>, len = -209989616}, method_val = {s = 0x7fffc4c7e7f0 "\300\207A", len = -209758064}, lr_val = {s = 0x0, len = 0}, r2_val = {s = 0x7f0ff37bd1c8 "\220X\177\363\017\177", len = 654934511},
          gr_val = {s = 0x4187c0 "1\355I\211\321^H\211\342H\203\344\360PTI\307\300\200\\n", len = -993524144}}
        next_hop = {user = {s = 0x0, len = 0}, passwd = {s = 0x0, len = -209263824}, host = {
            s = 0xa6f675 "2.0\r\nVia: SIP/2.0/UDP 213.148.135.2:5066;branch=z9hG4bKl5tuhsog51l5lt8lcos5l1lro\r\nCall-ID: s1htyc1umymu8ucsy8gortg8c165u65g@SoftX3000\r\nFrom: <sip:0211551490@213.148.135.2;user=phone>;tag=u5rl7o6m-CC-2"..., len = 0}, port = {s = 0x7f0ff3819580 "\002", len = 6432415}, params = {s = 0x7fffc4c7e570 "pn\250", len = -209989616}, sip_params = {s = 0x7fffc4c7e5b0 "D\346\307\304\377\177", len = 0}, headers = {s = 0x7fffc4c7e5dc "", len = 0},
          port_no = 28272, proto = 168, type = ERROR_URI_T, flags = 0, transport = {s = 0x920f0 <Address 0x920f0 out of bounds>, len = 724456}, ttl = {s = 0xb0de8 <Address 0xb0de8 out of bounds>, len = 654934511}, user_param = {
            s = 0x7fffc4c7e5f0 "pn\250", len = 5168840}, maddr = {s = 0x7fffc4c7e644 "", len = 6432415}, method = {s = 0xa86e70 "", len = 0}, lr = {s = 0x7fffc4c7e630 "\314\346\307\304\377\177", len = 0}, r2 = {
            s = 0x7fffc4c7e65c "\001", len = 0}, gr = {s = 0xa86e70 "", len = 0}, transport_val = {s = 0x7fffc4c7e644 "", len = 0}, ttl_val = {s = 0x7fffc4c7e650 "\220\346\307\304\377\177", len = 654934511}, user_param_val = {
            s = 0x7fffc4c7e670 "\220\346\307\304\377\177", len = -260260081}, maddr_val = {s = 0x7fffc4c7e6cc "\001", len = -209263824}, method_val = {s = 0xa86e70 "", len = 0}, lr_val = {s = 0x7fffc4c7e690 "\340\346\307\304\377\177",
            len = -289765062}, r2_val = {s = 0xa86e84 "0", len = -993532032}, gr_val = {s = 0x7fffc4c7e690 "\340\346\307\304\377\177", len = -260259959}}
        u = 0x7fffc4c7ea98
        port = 0
        dst_host = 0x7fffc4c7eac0
        i = 5678571
        flags = 0
        avp = 0x7fffc4c7ea10
        st = {flags = 0, id = 0, name = {n = 0, s = {s = 0x0, len = 0}, re = 0x0}, avp = 0x0}
        sct = 0x7f0ff386e330
        sjt = 0x7fffc4c7ea74
        rve = 0x7f0ff386e330
        mct = 0x7f0ff382d338
        rv = 0x0
        rv1 = 0x7fffc4c7ff30
        c1 = {cache_type = RV_CACHE_EMPTY, val_type = RV_NONE, c = {avp_val = {n = 0, s = {s = 0x0, len = 0}, re = 0x0}, pval = {rs = {s = 0x0, len = 0}, ri = 0, flags = 0}}, i2s = '\000' <repeats 21 times>}
        s = {s = 0x0, len = 0}
        srevp = {0x0, 0x0}
        mod_f_params = {{type = NOSUBTYPE, u = {number = 0, string = 0x0, str = {s = 0x0, len = 0}, data = 0x0, attr = 0x0, select = 0x0}}, {type = NOSUBTYPE, u = {number = 0, string = 0x0, str = {s = 0x0, len = 0}, data = 0x0,
              attr = 0x0, select = 0x0}}, {type = NOSUBTYPE, u = {number = 0, string = 0x0, str = {s = 0x0, len = 0}, data = 0x0, attr = 0x0, select = 0x0}}, {type = NOSUBTYPE, u = {number = 0, string = 0x0, str = {s = 0x0, len = 0},
              data = 0x0, attr = 0x0, select = 0x0}}, {type = NOSUBTYPE, u = {number = 0, string = 0x0, str = {s = 0x0, len = 0}, data = 0x0, attr = 0x0, select = 0x0}}, {type = NOSUBTYPE, u = {number = 0, string = 0x0, str = {s = 0x0,
                len = 0}, data = 0x0, attr = 0x0, select = 0x0}}, {type = NOSUBTYPE, u = {number = 0, string = 0x0, str = {s = 0x0, len = 0}, data = 0x0, attr = 0x0, select = 0x0}}, {type = NOSUBTYPE, u = {number = 0, string = 0x0,
              str = {s = 0x0, len = 0}, data = 0x0, attr = 0x0, select = 0x0}}}
        __FUNCTION__ = "do_action"
```

**Comment by miconda** [comment]
I pushed a patch to branches from 4.1 to master. If the issue is still there, then reopen this item.
