### ISSUE TITLE
Kamailio crashing when applying s.prefixes transformation on empty string

### ISSUE THREAD

**Issue by cmcom-gb** [kamailio/kamailio#2467]
### Description
Applying a simple `{s.prefixes}` transformation on a variable with an empty value crashes Kamailio. It is not specific to a particular SIP message being processed. 

#### Reproduction

```
request_route {
        $var(empty) = "";
        $var(result) = $(var(empty){s.prefixes});
        drop;
}
```

#### Debugging Data

```
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:514
No locals.
#1  0x00007f7309ab8712 in set_var_value (var=0x7f730b308cd0, value=0x7ffc716f1c10, flags=1) at pv_svar.c:137
        __func__ = "set_var_value"
#2  0x00007f7309b32c36 in pv_set_scriptvar (msg=0x7f730b328e20, param=0x7f730b308c10, op=254, val=0x7ffc716f1d10) at pv_core.c:2388
        avp_val = {n = 1235741648, s = {s = 0x562849a7ebd0 "X\213]\017s\177", len = -1}, re = 0x562849a7ebd0}
        flags = 1
        __func__ = "pv_set_scriptvar"
#3  0x00005628478470c5 in lval_pvar_assign (h=0x7ffc716f2710, msg=0x7f730b328e20, lv=0x7f730b308dd8, rv=0x7f730b3090f0) at core/lvalue.c:352
        pvar = 0x7f730b308bf8
        pval = {rs = {s = 0x562849a7ebd0 "X\213]\017s\177", len = -1}, ri = 0, flags = 4}
        r_avp = 0x1
        avp_val = {n = 1903108595, s = {s = 0x7ffc716f21f3 "", len = 1236653072}, re = 0x7ffc716f21f3}
        ret = 0
        v = 1903108968
        destroy_pval = 1
        __func__ = "lval_pvar_assign"
#4  0x0000562847847c93 in lval_assign (h=0x7ffc716f2710, msg=0x7f730b328e20, lv=0x7f730b308dd8, rve=0x7f730b3090e8) at core/lvalue.c:400
        rv = 0x7f730b3090f0
        ret = 0
        __func__ = "lval_assign"
#5  0x00005628478331c4 in do_action (h=0x7ffc716f2710, a=0x7f730b309818, msg=0x7f730b328e20) at core/action.c:1455
        ret = -5
        v = 0
        dst = {send_sock = 0x33340f5d8b00, to = {s = {sa_family = 1, sa_data = "\000\000\000\000\000\000\320\b\002\000\000\000\000"}, sin = {sin_family = 1, sin_port = 0, sin_addr = {s_addr = 0},
              sin_zero = "\320\b\002\000\000\000\000"}, sin6 = {sin6_family = 1, sin6_port = 0, sin6_flowinfo = 0, sin6_addr = {__in6_u = {__u6_addr8 = "\320\b\002\000\000\000\000\000`\366\265I(V\000",
                  __u6_addr16 = {2256, 2, 0, 0, 63072, 18869, 22056, 0}, __u6_addr32 = {133328, 0, 1236661856, 22056}}}, sin6_scope_id = 125344}, sas = {ss_family = 1,
              __ss_padding = "\000\000\000\000\000\000\320\b\002\000\000\000\000\000`\366\265I(V\000\000\240\351\001\000\000\000\000\000\340ֵI(V\000\000\000\213]\017s\177\000\000\001\000\000\000\000\000\000\000 \t\002\000\000\000\000\000`\366\265I(V\000\000\240\351\001\000\000\000\000\000\207p+\017s\177\000\000lֵI(V\000\000\222':\017s\177\000\000 x]\017s\177\000\000\b\000\000\000\000\000\000",
              __ss_align = 0}}, id = 254729950, send_flags = {f = 32627, blst_imask = 0}, proto = 0 '\000', proto_pad0 = 0 '\000', proto_pad1 = 12544}
        tmp = 0x3000000000 <error: Cannot access memory at address 0x3000000000>
        new_uri = 0x7ffc00000005 <error: Cannot access memory at address 0x7ffc00000005>
        end = 0x7f730f2b3c2e <__GI__IO_default_xsputn+206> "I\211F(\353\260\017\037@"
        crt = 0x7ffc00000000 <error: Cannot access memory at address 0x7ffc00000000>
        cmd = 0x7ffc716f2110
        len = 1203975572
        user = 22056
        uri = {user = {s = 0x7ffc00000000 <error: Cannot access memory at address 0x7ffc00000000>, len = 47}, passwd = {s = 0x562847bfa281 "(): ", len = 0}, host = {
            s = 0x562800000000 <error: Cannot access memory at address 0x562800000000>, len = 4}, port = {s = 0x7ffc716f21f0 "\001", len = 0}, params = {
            s = 0xd68 <error: Cannot access memory at address 0xd68>, len = 51}, sip_params = {s = 0x562847bfb1c0 "%s: %.*s%s%s%spreparing to run routing scripts...\n", len = 5}, headers = {
            s = 0x562847bfb022 "s]\n", len = 1203745266}, port_no = 23776, proto = 3933, type = 32627, flags = (unknown: 16), transport = {s = 0x7ffc716f27c0 "V\215uq\374\177", len = 1903109888}, ttl = {
            s = 0x562847bfb1c7 "s%s%s%spreparing to run routing scripts...\n", len = 1903108592}, user_param = {s = 0x562849b5d650 "P\002", len = 16}, maddr = {s = 0x7ffc716f27f0 "\260*oq\374\177",
            len = 1903109936}, method = {s = 0x333400020c00 <error: Cannot access memory at address 0x333400020c00>, len = 1236653808}, lr = {
            s = 0x333400020910 <error: Cannot access memory at address 0x333400020910>, len = 254505095}, r2 = {s = 0x1 <error: Cannot access memory at address 0x1>, len = 1236653808}, gr = {
            s = 0x7f730f5d8b00 <main_arena> "", len = 1}, transport_val = {s = 0x20910 <error: Cannot access memory at address 0x20910>, len = 1236661856}, ttl_val = {
            s = 0x1e9a0 <error: Cannot access memory at address 0x1e9a0>, len = 254505095}, user_param_val = {
            s = 0x562849b5d66c "10:23:43 /usr/sbin/kamailio[14412]: DEBUG: <core> [core/receive.c:379]: receive_msg(): preparing to run routing scripts...\n", len = 255469458}, maddr_val = {
            s = 0x7f730f5d7820 <_nl_C_locobj> " W]\017s\177", len = 8}, method_val = {s = 0x0, len = 254729950}, lr_val = {
            s = 0x3231343431000000 <error: Cannot access memory at address 0x3231343431000000>, len = 8187}, r2_val = {s = 0x0, len = 1236653648}, gr_val = {s = 0x562849b5f660 "", len = 257788672}}
        next_hop = {user = {s = 0x0, len = 160}, passwd = {s = 0x8c <error: Cannot access memory at address 0x8c>, len = 254513428}, host = {s = 0x7f730f3a0a0b "%H:%M:%S", len = 24}, port = {
            s = 0x7ffc716f2390 "\025", len = 1236653664}, params = {s = 0x562849b5d650 "P\002", len = 1236653056}, sip_params = {s = 0x7f730f5d8b00 <main_arena> "", len = 0}, headers = {
            s = 0x20c00 <error: Cannot access memory at address 0x20c00>, len = 1236653808}, port_no = 2320, proto = 2, type = ERROR_URI_T,
          flags = (URI_USER_NORMALIZE | URI_SIP_USER_PHONE | unknown: 254505092), transport = {s = 0x1 <error: Cannot access memory at address 0x1>, len = 1236653072}, ttl = {s = 0x7ffc716f23b0 "`ֵI(V",
            len = 257773696}, user_param = {s = 0x562800000001 <error: Cannot access memory at address 0x562800000001>, len = 1236653072}, maddr = {s = 0x0, len = 257773696}, method = {
            s = 0x562849b5d410 "X\213]\017s\177", len = 1}, lr = {s = 0xffffffff <error: Cannot access memory at address 0xffffffff>, len = 11}, r2 = {s = 0x562849b5d410 "X\213]\017s\177",
            len = 1903109256}, gr = {s = 0x15 <error: Cannot access memory at address 0x15>, len = 254947161}, transport_val = {s = 0x15 <error: Cannot access memory at address 0x15>, len = 1203975024},
          ttl_val = {s = 0x562847c37125 "", len = 254734910}, user_param_val = {
            s = 0x562849b5d660 "<135>Sep  2 10:23:43 /usr/sbin/kamailio[14412]: DEBUG: <core> [core/receive.c:379]: receive_msg(): preparing to run routing scripts...\n", len = 8180}, maddr_val = {
            s = 0x6 <error: Cannot access memory at address 0x6>, len = 0}, method_val = {s = 0x7ffc716f2660 "+", len = 254734910}, lr_val = {s = 0x7f730f5d5ce0 <_nl_C_LC_TIME> "-(:\017s\177",
            len = 8180}, r2_val = {s = 0x6 <error: Cannot access memory at address 0x6>, len = 1903109184}, gr_val = {s = 0x7ffc716f2690 "+", len = 1903109200}}
        u = 0xffffffffffffffff
        port = 18371
        dst_host = 0x562849b5d420
---Type <return> to continue, or q <return> to quit---
        i = 0
        flags = 32764
        avp = 0x7ffc00000000
        st = {flags = 1903108472, id = 32764, name = {n = 16, s = {s = 0x3000000010 <error: Cannot access memory at address 0x3000000010>, len = 1903108512}, re = 0x3000000010}, avp = 0x716f2560}
        sct = 0x24
        sjt = 0xd68
        rve = 0x0
        mct = 0x562849b5d410
        rv = 0x0
        rv1 = 0x0
        c1 = {cache_type = 1235727904, val_type = 22056, c = {avp_val = {n = 1903109232, s = {s = 0x7ffc716f2470 "\320\b\002", len = 1235727904}, re = 0x7ffc716f2470}, pval = {rs = {
                s = 0x7ffc716f2470 "\320\b\002", len = 1235727904}, ri = 965624, flags = 0}}, i2s = "\330\364\016\000\000\000\000\000\004\000\000\000\000\000\000\000\000'oq\374\177"}
        s = {s = 0x7ffc716f2610 "\025", len = 1203745216}
        srevp = {0x7f730f5d5ce0 <_nl_C_LC_TIME>, 0x7ffc716f260f}
        evp = {data = 0x0, obuf = {s = 0x0, len = 0}, rcv = 0x0, dst = 0x0, req = 0x0, rpl = 0x0, rplcode = 0, mode = 0}
        mod_f_params = {{type = NOSUBTYPE, u = {number = 0, string = 0x0, str = {s = 0x0, len = 0}, data = 0x0, attr = 0x0, select = 0x0}}, {type = NOSUBTYPE, u = {number = 0, string = 0x0, str = {
                s = 0x0, len = 0}, data = 0x0, attr = 0x0, select = 0x0}}, {type = NOSUBTYPE, u = {number = 0, string = 0x0, str = {s = 0x0, len = 0}, data = 0x0, attr = 0x0, select = 0x0}}, {
            type = NOSUBTYPE, u = {number = 0, string = 0x0, str = {s = 0x0, len = 0}, data = 0x0, attr = 0x0, select = 0x0}}, {type = NOSUBTYPE, u = {number = 0, string = 0x0, str = {s = 0x0, len = 0},
              data = 0x0, attr = 0x0, select = 0x0}}, {type = NOSUBTYPE, u = {number = 0, string = 0x0, str = {s = 0x0, len = 0}, data = 0x0, attr = 0x0, select = 0x0}}, {type = NOSUBTYPE, u = {
              number = 0, string = 0x0, str = {s = 0x0, len = 0}, data = 0x0, attr = 0x0, select = 0x0}}, {type = NOSUBTYPE, u = {number = 0, string = 0x0, str = {s = 0x0, len = 0}, data = 0x0,
              attr = 0x0, select = 0x0}}}
        __func__ = "do_action"
#6  0x0000562847835175 in run_actions (h=0x7ffc716f2710, a=0x7f730b3089a8, msg=0x7f730b328e20) at core/action.c:1581
        t = 0x7f730b309818
        ret = 1
        tvb = {tv_sec = 0, tv_usec = 0}
        tve = {tv_sec = 0, tv_usec = 0}
        tz = {tz_minuteswest = 187862560, tz_dsttime = 32627}
        tdiff = 0
        __func__ = "run_actions"
#7  0x00005628478359c3 in run_top_route (a=0x7f730b3089a8, msg=0x7f730b328e20, c=0x0) at core/action.c:1666
        ctx = {rec_lev = 1, run_flags = 0, last_retcode = 0, jmp_env = {{__jmpbuf = {94731002421834, 4111138437774347241, 0, 140132152914432, 94731002488408, 7, 4111138437721918441, 7684794046908238825},
              __mask_was_saved = 0, __saved_mask = {__val = {0, 0, 140132152696542, 3616729374520246273, 8187, 0, 140722211596240, 140722212015446, 0, 4294967296, 1551136975241484032, 140722212015446,
                  94731002421834, 0, 140132152914432, 94731002488408}}}}}
        p = 0x7ffc716f2710
        ret = 0
        sfbk = 0
#8  0x000056284797fb37 in receive_msg (
    buf=0x562847e9d9a0 <buf> "OPTIONS sip:10.14.33.42:5060 SIP/2.0\r\nVia: SIP/2.0/UDP 10.14.34.11;branch=z9hG4bK201.26407cf1", '0' <repeats 24 times>, ".0\r\nTo: <sip:10.14.33.42:5060>\r\nFrom: <sip:keepalive@sip.test.com>;tag=3393f0703fb0cca"..., len=324, rcv_info=0x7ffc716f2bc0) at core/receive.c:423
        msg = 0x7f730b328e20
        ctx = {rec_lev = 1903110832, run_flags = 32764, last_retcode = 48, jmp_env = {{__jmpbuf = {140722211596984, 140722211596736, 0, 140132152914432, 94731002488408, 0, 94731002272776,
                94731002278608}, __mask_was_saved = 1903110848, __saved_mask = {__val = {140722211596800, 140722211596944, 94730998676934, 1, 140130399476408, 1, 4, 6198078064, 140130399476408,
                  140722211596912, 94730998676774, 94731035333648, 140130399476408, 21, 7097619256, 140722211596976}}}}}
        bctx = 0x0
        ret = -1
        tvb = {tv_sec = 1599035023, tv_usec = 724184}
        tve = {tv_sec = 0, tv_usec = 0}
        diff = 0
        inb = {
          s = 0x562847e9d9a0 <buf> "OPTIONS sip:10.14.33.42:5060 SIP/2.0\r\nVia: SIP/2.0/UDP 10.14.34.11;branch=z9hG4bK201.26407cf1", '0' <repeats 24 times>, ".0\r\nTo: <sip:10.14.33.42:5060>\r\nFrom: <sip:keepalive@sip.test.com>;tag=3393f0703fb0cca"..., len = 324}
        netinfo = {data = {s = 0x0, len = 0}, rcv = 0x0, dst = 0x0}
        keng = 0x0
        evp = {data = 0x7ffc716f28f0, obuf = {s = 0x0, len = 0}, rcv = 0x7ffc716f2bc0, dst = 0x0, req = 0x0, rpl = 0x0, rplcode = 0, mode = 0}
        cidlockidx = 0
        cidlockset = 0
        errsipmsg = 0
        exectime = 1
        __func__ = "receive_msg"
#9  0x0000562847871baa in udp_rcv_loop () at core/udp_server.c:543
        len = 324
        buf = "OPTIONS sip:10.14.33.42:5060 SIP/2.0\r\nVia: SIP/2.0/UDP 10.14.34.11;branch=z9hG4bK201.26407cf1", '0' <repeats 24 times>, ".0\r\nTo: <sip:10.14.33.42:5060>\r\nFrom: <sip:keepalive@sip.test.com>---Type <return> to continue, or q <return> to quit---
;tag=3393f0703fb0cca"...
        tmp = 0x1 <error: Cannot access memory at address 0x1>
        fromaddr = 0x7f730b3201f0
        fromaddrlen = 16
        rcvi = {src_ip = {af = 2, len = 4, u = {addrl = {186781194, 0}, addr32 = {186781194, 0, 0, 0}, addr16 = {3594, 2850, 0, 0, 0, 0, 0, 0}, addr = "\n\016\"\v", '\000' <repeats 11 times>}}, dst_ip = {
            af = 2, len = 4, u = {addrl = {706809354, 0}, addr32 = {706809354, 0, 0, 0}, addr16 = {3594, 10785, 0, 0, 0, 0, 0, 0}, addr = "\n\016!*", '\000' <repeats 11 times>}}, src_port = 5060,
          dst_port = 5060, proto_reserved1 = 0, proto_reserved2 = 0, src_su = {s = {sa_family = 2, sa_data = "\023\304\n\016\"\v\000\000\000\000\000\000\000"}, sin = {sin_family = 2, sin_port = 50195,
              sin_addr = {s_addr = 186781194}, sin_zero = "\000\000\000\000\000\000\000"}, sin6 = {sin6_family = 2, sin6_port = 50195, sin6_flowinfo = 186781194, sin6_addr = {__in6_u = {
                  __u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, sin6_scope_id = 0}, sas = {ss_family = 2,
              __ss_padding = "\023\304\n\016\"\v", '\000' <repeats 111 times>, __ss_align = 0}}, bind_address = 0x7f730b312730, proto = 1 '\001', proto_pad0 = 0 '\000', proto_pad1 = 0}
        evp = {data = 0x0, obuf = {s = 0x0, len = 0}, rcv = 0x0, dst = 0x0, req = 0x0, rpl = 0x0, rplcode = 0, mode = 0}
        printbuf = "OPTIONS sip:10.14.33.42:5060 SIP/2.0 0D  0A Via: SIP/2.0/UDP 10.14.34.11;branch=z9hG4bK201.26407cf10000000>Wܾ\206\025 -oq\374\177\000\000\305ҾG(V", '\000' <repeats 11 times>, "\062\062\017s\177\000\000X\246\300G(V\000\000\a\000\000\000\000\000\000\000\340-oq\374\177\000\000\061ɐG(V\000\000\200-oq\374\177\000\000\370$\265G\004\000\000\000\003\000\000\000\000\000\000\000\307\360\276"...
        i = 100
        j = 106
        l = 4
        __func__ = "udp_rcv_loop"
#10 0x00005628477c556c in main_loop () at main.c:1683
        i = 1
        pid = 0
        si = 0x7f730b312730
        si_desc = "udp receiver child=1 sock=10.14.33.42:5060\000\000\n\000\000\000\002\000\000\000\023\000\000\000\000\027>Wܾ\206\025\000\000\000\000\000\000\000\000跻G(V", '\000' <repeats 11 times>, "\062\062\017s\177\000\000S\246\300G(V\000\000\000\000\000^\000\000\000\000`0oq\374\177\000\000\020\252\242G(V\000"
        nrprocs = 2
        woneinit = 1
        __func__ = "main_loop"
#11 0x00005628477cfe00 in main (argc=11, argv=0x7ffc716f35a8) at main.c:2856
        cfg_stream = 0x562849a74010
        c = -1
        r = 0
        tmp = 0x7ffc716f4e69 ""
        tmp_len = 32764
        port = 255191781
        proto = 32627
        ahost = 0x0
        aport = 0
        options = 0x562847bbe498 ":f:cm:M:dVIhEeb:l:L:n:vKrRDTN:W:w:t:u:g:P:G:SQ:O:a:A:x:X:Y:"
        ret = -1
        seed = 1197033085
        rfd = 4
        debug_save = 0
        debug_flag = 0
        dont_fork_cnt = 0
        n_lst = 0x7f730ff1a630
        p = 0x7f730ff1a000 "\177ELF\002\001\001"
        st = {st_dev = 19, st_ino = 48223049, st_nlink = 2, st_mode = 16888, st_uid = 108, st_gid = 112, __pad0 = 0, st_rdev = 0, st_size = 40, st_blksize = 4096, st_blocks = 0, st_atim = {
            tv_sec = 1599035016, tv_nsec = 629096950}, st_mtim = {tv_sec = 1599035016, tv_nsec = 629096950}, st_ctim = {tv_sec = 1599035016, tv_nsec = 629096950}, __glibc_reserved = {0, 0, 0}}
        tbuf = "\b\367\023\020s\177\000\000\030\063oq\374\177\000\000\024\063oq\374\177\000\000\000\000\000\000\000\000\000\000'\005:\017s\177\000\000\260\064oq\374\177\000\000\030\063oq\374\177\000\000&\260be\000\000\000\000\300\212\225\001\000\000\000\000\230\202uq\374\177\000\000\360\063oq\374\177\000\000\250\201uq\374\177\000\000\024\063oq\374\177\000\000\340\063oq\374\177\000\000\060\367\023\020s\177\000\000\001\000\000\000\000\000\000\000\340\360^\017", '\000' <repeats 36 times>, "\220\372\023\020s\177\000\000\200\064oq\374\177\000\000\340\064oq\374\177", '\000' <repeats 18 times>...
        option_index = 0
        long_options = {{name = 0x562847bc0526 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x562847bbbc6c "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x562847bc052b "alias",
            has_arg = 1, flag = 0x0, val = 1024}, {name = 0x562847bc0531 "subst", has_arg = 1, flag = 0x0, val = 1025}, {name = 0x562847bc0537 "substdef", has_arg = 1, flag = 0x0, val = 1026}, {
            name = 0x562847bc0540 "substdefs", has_arg = 1, flag = 0x0, val = 1027}, {name = 0x562847bc054a "server-id", has_arg = 1, flag = 0x0, val = 1028}, {name = 0x562847bc0554 "loadmodule",
            has_arg = 1, flag = 0x0, val = 1029}, {name = 0x562847bc055f "modparam", has_arg = 1, flag = 0x0, val = 1030}, {name = 0x562847bc0568 "log-engine", has_arg = 1, flag = 0x0, val = 1031}, {
            name = 0x562847bc0573 "debug", has_arg = 1, flag = 0x0, val = 1032}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        __func__ = "main"
```

#### SIP Traffic

Any SIP traffic will do, as long as this particular scenario is hit, for whatever reason. Could be buggy business logic.

### Possible Solutions

The only thing I could think of is to place the transformation inside an `if` statement which checks for an empty value of the variable the `{s.prefixes]` transformation is being applied to.

### Additional Information

I've tested this with Kamailio 5.1 and 5.4, and both have this issue. 

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.4.0 (x86_64/linux)
version: kamailio 5.1.10 (x86_64/linux)
```

* **Operating System**:

```
Kamailio 5.1.10 -> Debian GNU/Linux 9.13 (stretch)
Kamailio 5.4.0 -> Debian GNU/Linux 9.8 (stretch)
```

**Comment by miconda** [comment]
Thanks for the report, the issue should be fixed on all maintained branches by the commits referenced above.
