### ISSUE TITLE
kamctl - maintenance for dbtextdb.py tool

### ISSUE THREAD

**Issue by miconda** [kamailio/kamailio#2469]
**kamctl** include a python tool that is parsing SQL statements to do operations over the **db_text** files, for the common db operations (e.g., insert, delete). It is located at:

  * https://github.com/kamailio/kamailio/tree/master/utils/kamctl/dbtextdb

The tool was contributed long time ago and not kept up to date, being known not to work with Python3 (e.g., #2464).

This issue is created to see if someone has the interest to pick up the maintenance of this tool, if not it will be removed from kamctl.

Note that db_text works with text files, so it is not necessary to have a tool for managing the content of these files, they can be simply updated with any text editor.

**Comment by Evsio0n** [comment]
I got same issue here, let me figure out wether can be fixed.
``` bash
root@evsio0nHK:~# kamctl add evsio0n 123
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/kamailio//kamctl/dbtextdb/dbtextdb.py", line 1243, in <module>
    main(sys.argv)
  File "/usr/lib/x86_64-linux-gnu/kamailio//kamctl/dbtextdb/dbtextdb.py", line 1230, in main
    dataset = conn.Execute(' '.join(argv[1:]))
  File "/usr/lib/x86_64-linux-gnu/kamailio//kamctl/dbtextdb/dbtextdb.py", line 423, in Execute
    self.WriteTempTable()
  File "/usr/lib/x86_64-linux-gnu/kamailio//kamctl/dbtextdb/dbtextdb.py", line 1138, in WriteTempTable
    self.temp_file.write(header.strip() + '\n')
  File "/usr/lib/python3.9/tempfile.py", line 613, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
ERROR: introducing the new user 'evsio0n' to the database failed
root@evsio0nHK:~#
```

**Comment by miconda** [comment]
Thanks for suggesting the changes, I pushed a commit for them.

I assume now is ok, so I close this one. If not, reopen.
