### ISSUE TITLE
core on simple config file

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#2562]
### Description
For test purpose, i created a config file with this content
```
listen=udp:eth0:11000
```

When I start Kamailio using the command I got core
```
[centos@ip-100-86-32-7 ~]$ kamailio -f kamailio.cfg 
Segmentation fault (core dumped)
[centos@ip-100-86-32-7 ~]$ 
```

#### Debugging Data

```
(gdb) bt full
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x00000000005979fb in ksr_shutdown_phase_init () at core/sr_module.c:118
        __func__ = "ksr_shutdown_phase_init"
#2  0x0000000000431181 in main (argc=3, argv=0x7fffffffe388) at main.c:2545
        cfg_stream = 0xba02b0
        c = -1
        r = -7712
        tmp = 0x9c0000009c0 <error: Cannot access memory at address 0x9c0000009c0>
        tmp_len = 32767
        port = -134224128
        proto = 0
        ahost = 0x0
        aport = 0
        options = 0x7e3488 ":f:cm:M:dVIhEeb:l:L:n:vKrRDTN:W:w:t:u:g:P:G:SQ:O:a:A:x:X:Y:"
        ret = -1
        seed = 3173775974
        rfd = 4
        debug_save = 0
        debug_flag = 0
        dont_fork_cnt = 0
        n_lst = 0x7ffff7ffe700
        p = 0x7ffff70f9205 <handle_intel.constprop+197> "H\205\300uf\213t$\004M\215\216\244"
        st = {st_dev = 0, st_ino = 0, st_nlink = 0, st_mode = 0, st_uid = 0, st_gid = 0, __pad0 = 0, st_rdev = 0, st_size = 0, st_blksize = 0, st_blocks = 0, st_atim = {
            tv_sec = 0, tv_nsec = 0}, st_mtim = {tv_sec = 0, tv_nsec = 0}, st_ctim = {tv_sec = 0, tv_nsec = 0}, __glibc_reserved = {0, 0, 0}}
        tbuf = "|\343\006\367\377\177\000\000ء\377\367\377\177\000\000\000\000\000\000 ", '\000' <repeats 19 times>, " O\335\367\377\177\000\000`\340\377\377\377\177\000\000\a\000\000\000\000\000\000\000\330D\335\367\377\177\000\000\a\000\000\000\t\000\000\000\220\331\377\367\377\177\000\000\314\000\336\367\377\177\000\000\000\000\000\000\000\000\000\000\370\016\336\367\377\177\000\000\260\337\377\377\377\177\000\000\240\343\006\367\377\177\000\000\300\263\376\367\377\177\000\000\000\000\000\000\000\000\000\000\060\340\377\377\377\177", '\000' <repeats 26 times>, "HG\335\367\377\177\000\000\270\344\377\367\377\177\000\000\060\340\377\377\377\177\000\000\000"...
        option_index = 0
        long_options = {{name = 0x7e55f6 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x7e0bc1 "version", has_arg = 0, flag = 0x0, val = 118}, {
            name = 0x7e55fb "alias", has_arg = 1, flag = 0x0, val = 1024}, {name = 0x7e5601 "subst", has_arg = 1, flag = 0x0, val = 1025}, {name = 0x7e5607 "substdef", 
            has_arg = 1, flag = 0x0, val = 1026}, {name = 0x7e5610 "substdefs", has_arg = 1, flag = 0x0, val = 1027}, {name = 0x7e561a "server-id", has_arg = 1, 
            flag = 0x0, val = 1028}, {name = 0x7e5624 "loadmodule", has_arg = 1, flag = 0x0, val = 1029}, {name = 0x7e562f "modparam", has_arg = 1, flag = 0x0, 
            val = 1030}, {name = 0x7e5638 "log-engine", has_arg = 1, flag = 0x0, val = 1031}, {name = 0x7e5643 "debug", has_arg = 1, flag = 0x0, val = 1032}, {name = 0x0, 
            has_arg = 0, flag = 0x0, val = 0}}
        __func__ = "main"
(gdb) info locals
No symbol table info available.
(gdb) list
1890			+((!sctp_disable)?sctp_listeners:0)
1891	#endif
1892			;
1893	}
1894	
1895	int main(int argc, char** argv)
1896	{
1897	
1898		FILE* cfg_stream;
1899		int c,r;
(gdb) 
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
[centos@ip-100-86-32-7 ~]$ kamailio -v
version: kamailio 5.5.0-dev3 (x86_64/linux) e9624b
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: e9624b 
compiled on 04:01:18 Nov 10 2020 with gcc 8.3.1
```

* **Operating System**:

```
[centos@ip-100-86-32-7 ~]$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```

**Comment by miconda** [comment]
Can you test with latest master (commit b7d42f248bef70a06d8ae23f4a7652fd3f0e4e61)?

**Comment by miconda** [comment]
Reopen if the same issue happens after the commit referenced above or open a new one of a different problem shows up.

**Comment by sergey-safarov** [comment]
I messed your message.
Just tested commit and I not see issue more.
