### ISSUE TITLE
Kamailio 5.6.0 crash when removing non-existing node from the dispatcher

### ISSUE THREAD

**Issue by denyspozniak** [kamailio/kamailio#3199]
### Description

When deleting a node that does not resolve through the DNS and that does not exist in the dispatcher table, a Kamailio crash occurs.

#### Reproduction

1. Create set id with one existing node in dispatcher table (DB MySQL) (for example sip:10.1.0.6 in set 200)  
2. Reload dispatcher table:
`kamcmd dispatcher.reload`
3. Delete a non-existent and non-resolvable node via kamcmd:
`kamcmd dispatcher.remove 200 sip:127.0.0.1.test`
ERROR: read reply failed: Success (0)
5. Kamailio crashed

#### Debugging Data

  bt full
  info locals
  list

```
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/sbin/kamailio...Reading symbols from /usr/lib/debug/usr/sbin/kamailio.debug...done.
done.
[New LWP 28559]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/sbin/kamailio -DD -P /run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fd7f6705b0c in ds_filter_dest_cb (node=0x7fd7d6213270, i=0, arg=0x7ffe0e9c8a60) at dispatch.c:2660
2660            if(node->id == filter_arg->setid && node->dlist[i].uri.len == filter_arg->dest->uri.len &&
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 elfutils-libelf-0.176-5.el7.x86_64 elfutils-libs-0.176-5.el7.x86_64 glibc-2.17-326.el7_9.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-54.el7_9.x86_64 libattr-2.4.46-13.el7.x86_64 libcap-2.22-11.el7.x86_64 libcom_err-1.42.9-19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libselinux-2.5-15.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 mariadb-libs-5.5.68-1.el7.x86_64 openssl-libs-1.0.2k-25.el7_9.x86_64 pcre-8.32-17.el7.x86_64 systemd-libs-219-78.el7_9.5.x86_64 xz-libs-5.2.2-2.el7_9.x86_64 zlib-1.2.7-20.el7_9.x86_64
(gdb) bt full
#0  0x00007fd7f6705b0c in ds_filter_dest_cb (node=0x7fd7d6213270, i=0, arg=0x7ffe0e9c8a60) at dispatch.c:2660
        filter_arg = 0x7ffe0e9c8a60
        __FUNCTION__ = "ds_filter_dest_cb"
#1  0x00007fd7f66dc077 in ds_iter_set (node=0x7fd7d6213270, ds_action_cb=0x7fd7f6705a8b <ds_filter_dest_cb>, ds_action_arg=0x7ffe0e9c8a60) at dispatch.c:213
        i = 0
#2  0x00007fd7f66dc050 in ds_iter_set (node=0x7fd7d62144d0, ds_action_cb=0x7fd7f6705a8b <ds_filter_dest_cb>, ds_action_arg=0x7ffe0e9c8a60) at dispatch.c:210
        i = 1
#3  0x00007fd7f66dc050 in ds_iter_set (node=0x7fd7d6211e08, ds_action_cb=0x7fd7f6705a8b <ds_filter_dest_cb>, ds_action_arg=0x7ffe0e9c8a60) at dispatch.c:210
        i = 1
#4  0x00007fd7f66dc050 in ds_iter_set (node=0x7fd7d620e6c0, ds_action_cb=0x7fd7f6705a8b <ds_filter_dest_cb>, ds_action_arg=0x7ffe0e9c8a60) at dispatch.c:210
        i = 1
#5  0x00007fd7f66dc050 in ds_iter_set (node=0x7fd7d620bf90, ds_action_cb=0x7fd7f6705a8b <ds_filter_dest_cb>, ds_action_arg=0x7ffe0e9c8a60) at dispatch.c:210
        i = 0
#6  0x00007fd7f6706252 in ds_remove_dst (group=200, address=0x7ffe0e9c8b40) at dispatch.c:2691
        setn = 7
        filter_arg = {setid = 200, dest = 0x0, setn = 0x7ffe0e9c8a80}
        dp = 0x0
        __FUNCTION__ = "ds_remove_dst"
#7  0x00007fd7f66d72d1 in dispatcher_rpc_remove (rpc=0x7fd7f6d93620 <binrpc_callbacks>, ctx=0x7ffe0e9c8c40) at dispatcher.c:1982
        group = 200
        dest = {s = 0x208dcc3 "sip:127.0.0.1.test", len = 18}
        __FUNCTION__ = "dispatcher_rpc_remove"
#8  0x00007fd7f6b640dc in process_rpc_req (buf=0x208dca4 "\241\003+\030\234\243\221\221\022dispatcher.remove", size=50, bytes_needed=0x7ffe0e9c8e8c, sh=0x7ffe0e9c8df0, saved_state=0x209dca8) at binrpc_run.c:688
        err = 0
        val = {name = {s = 0x100c8 <Address 0x100c8 out of bounds>, len = 4312272}, type = 1, u = {strval = {s = 0x208dcad "dispatcher.remove", len = 17}, fval = 1.6865036056773515e-316, intval = 34135213, end = 34135213}}
        rpc_e = 0x7fd7fb8c3af0
        f_ctx = {in = {ctx = {tlen = 43, cookie = 412918673, type = 0, flags = 1, offset = 43, in_struct = 0, in_array = 0}, s = 0x208dcd6 "", end = 0x208dcd6 "", record_no = 2, in_struct = 0}, out = {pkt = {body = 0x209dd40 "", end = 0x20a5d40 "", crt = 0x209dd40 ""}, structs = {
              next = 0x7ffe0e9c8c90, prev = 0x7ffe0e9c8c90}}, send_h = 0x7ffe0e9c8df0, method = 0x208dcad "dispatcher.remove", gc = 0x0, replied = 0, err_code = 0, err_phrase = {s = 0x0, len = 0}}
        ctx = 0x7ffe0e9c8c40
        __FUNCTION__ = "process_rpc_req"
#9  0x00007fd7f6b5910e in handle_stream_read (s_c=0x208dc70, idx=-1) at io_listener.c:512
        bytes_free = 65535
        bytes_read = 50
        bytes_needed = 32727
        bytes_processed = 1
        r = 0x208dc90
        sh = {fd = 10, type = 0, from = {sa_in = {s = {sa_family = 28688, sa_data = "x\373\327\177\000\000_zm\000\000\000\000"}, sin = {sin_family = 28688, sin_port = 64376, sin_addr = {s_addr = 32727}, sin_zero = "_zm\000\000\000\000"}, sin6 = {sin6_family = 28688, sin6_port = 64376,
                sin6_flowinfo = 32727, sin6_addr = {__in6_u = {__u6_addr8 = "_zm\000\000\000\000\000\020px\373\002\000\000", __u6_addr16 = {31327, 109, 0, 0, 28688, 64376, 2, 0}, __u6_addr32 = {7174751, 0, 4218974224, 2}}}, sin6_scope_id = 245104641}, sas = {ss_family = 28688,
                __ss_padding = "x\373\327\177\000\000_zm\000\000\000\000\000\020px\373\002\000\000\000\001\000\234\016\376\177\000\000\235\354\234\370\327\177\000\000@\364{\373\327\177", '\000' <repeats 12 times>, "\200\000\000\000\000\000\200\317k\000\000\000\000\000\200\245\r\000\000\000\000\000\200\060\024\000\000\000\000\000\001\000\000\000\000\000\000\000\250\a\373\325\327\177\000\000\004\000\000\000\000\000\000\000X\243\214\373\000\000\000", __ss_align = 4540108464}}, sa_un = {sun_family = 28688,
              sun_path = "x\373\327\177\000\000_zm\000\000\000\000\000\020px\373\002\000\000\000\001\000\234\016\376\177\000\000\235\354\234\370\327\177\000\000@\364{\373\327\177", '\000' <repeats 12 times>, "\200\000\000\000\000\000\200\317k\000\000\000\000\000\200\245\r\000\000\000\000\000\200\060\024\000\000\000\000\000\001\000\000\000\000\000\000\000\250\a\373\325\327\177\000\000\004\000\000\000\000"}}, from_len = 0}
        __FUNCTION__ = "handle_stream_read"
#10 0x00007fd7f6b5aebe in handle_io (fm=0x7fd7fb8c8db0, events=1, idx=-1) at io_listener.c:708
        ret = 1
        __FUNCTION__ = "handle_io"
#11 0x00007fd7f6b51ca2 in io_wait_loop_epoll (h=0x7fd7f6d83340 <ctl_io_h>, t=10, repeat=0) at ../../core/io_wait.h:1070
        n = 1
        r = 0
        fm = 0x7fd7fb8c8db0
        revents = 1
        __FUNCTION__ = "io_wait_loop_epoll"
#12 0x00007fd7f6b55dfb in io_listen_loop (fd_no=1, cs_lst=0x2068ac0) at io_listener.c:281
        max_fd_no = 239
        poll_err = 0x0
        poll_method = 2
        cs = 0x0
        type = 2
        __FUNCTION__ = "io_listen_loop"
#13 0x00007fd7f6b7453b in mod_child (rank=0) at ctl.c:338
        pid = 0
        cs = 0x80000000000000ee
        rpc_handler = 1
        __FUNCTION__ = "mod_child"
#14 0x00000000005d0d80 in init_mod_child (m=0x7fd7fb82b600, rank=0) at core/sr_module.c:877
        ret = 0
        __FUNCTION__ = "init_mod_child"
#15 0x00000000005d09d0 in init_mod_child (m=0x7fd7fb82bc38, rank=0) at core/sr_module.c:870
        ret = 0
        __FUNCTION__ = "init_mod_child"
#16 0x00000000005d09d0 in init_mod_child (m=0x7fd7fb82d710, rank=0) at core/sr_module.c:870
        ret = 0
        __FUNCTION__ = "init_mod_child"
#17 0x00000000005d09d0 in init_mod_child (m=0x7fd7fb82e178, rank=0) at core/sr_module.c:870
        ret = 0
        __FUNCTION__ = "init_mod_child"
#18 0x00000000005d09d0 in init_mod_child (m=0x7fd7fb82e7e8, rank=0) at core/sr_module.c:870
        ret = 0
---Type <return> to continue, or q <return> to quit---
        __FUNCTION__ = "init_mod_child"
#19 0x00000000005d09d0 in init_mod_child (m=0x7fd7fb82f5f8, rank=0) at core/sr_module.c:870
        ret = 0
        __FUNCTION__ = "init_mod_child"
#20 0x00000000005d09d0 in init_mod_child (m=0x7fd7fb833730, rank=0) at core/sr_module.c:870
        ret = 32
        __FUNCTION__ = "init_mod_child"
#21 0x00000000005d09d0 in init_mod_child (m=0x7fd7fb834b30, rank=0) at core/sr_module.c:870
        ret = 0
        __FUNCTION__ = "init_mod_child"
#22 0x00000000005d1547 in init_child (rank=0) at core/sr_module.c:931
        ret = -74709488
        type = 0x835ed5 "PROC_MAIN"
        __FUNCTION__ = "init_child"
#23 0x000000000042dc7d in main_loop () at main.c:1841
        i = 8
        pid = 28555
        si = 0x0
        si_desc = "udp receiver child=7 sock=10.1.131.126:5060\000\327\177\000\000\200\264\211\373\327\177\000\000P\247\203\373\327\177\000\000\000\235\234\016\376\177\000\000 \202\202\373\327\177\000\000\360\256\201\000\000\000\000\000\370\240\211\373\327\177\000\000c\276\201\000\000\000\000\000\373\257\201\000\000\000\000\000\004\000\000\000\000\000\000\000\000p\367\325\327\177\000"
        nrprocs = 8
        woneinit = 1
        __FUNCTION__ = "main_loop"
#24 0x00000000004377eb in main (argc=10, argv=0x7ffe0e9ca358) at main.c:3074
        cfg_stream = 0x1fb1670
        c = -1
        r = 0
        tmp = 0x7ffe0e9cbf07 ""
        tmp_len = 1472
        port = 960
        proto = 32727
        ahost = 0x0
        aport = 0
        options = 0x7f3c80 ":f:cm:M:dVIhEeb:l:L:n:vKrRDTN:W:w:t:u:g:P:G:SQ:O:a:A:x:X:Y:"
        ret = -1
        seed = 751594692
        rfd = 4
        debug_save = 0
        debug_flag = 0
        dont_fork_cnt = 2
        n_lst = 0x7ffe0e9ca210
        p = 0xf0b5ff <Address 0xf0b5ff out of bounds>
        st = {st_dev = 20, st_ino = 14179, st_nlink = 2, st_mode = 16832, st_uid = 996, st_gid = 992, __pad0 = 0, st_rdev = 0, st_size = 40, st_blksize = 4096, st_blocks = 0, st_atim = {tv_sec = 1645116507, tv_nsec = 547546400}, st_mtim = {tv_sec = 1658752241, tv_nsec = 765745118},
          st_ctim = {tv_sec = 1658752241, tv_nsec = 765745118}, __unused = {0, 0, 0}}
        tbuf = '\000' <repeats 392 times>...
        option_index = 0
        long_options = {{name = 0x7f60af "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x7f0f54 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x7f60b4 "alias", has_arg = 1, flag = 0x0, val = 1024}, {name = 0x7f60ba "subst", has_arg = 1, flag = 0x0, val = 1025}, {
            name = 0x7f60c0 "substdef", has_arg = 1, flag = 0x0, val = 1026}, {name = 0x7f60c9 "substdefs", has_arg = 1, flag = 0x0, val = 1027}, {name = 0x7f60d3 "server-id", has_arg = 1, flag = 0x0, val = 1028}, {name = 0x7f60dd "loadmodule", has_arg = 1, flag = 0x0, val = 1029}, {
            name = 0x7f60e8 "modparam", has_arg = 1, flag = 0x0, val = 1030}, {name = 0x7f60f1 "log-engine", has_arg = 1, flag = 0x0, val = 1031}, {name = 0x7f60fc "debug", has_arg = 1, flag = 0x0, val = 1032}, {name = 0x7f6102 "cfg-print", has_arg = 0, flag = 0x0, val = 1033}, {
            name = 0x7f610c "atexit", has_arg = 1, flag = 0x0, val = 1034}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        __FUNCTION__ = "main"




(gdb) info locals
filter_arg = 0x7ffe0e9c8a60
__FUNCTION__ = "ds_filter_dest_cb"


(gdb) list
2655    /* callback for removing nodes based on setid & address */
2656    void ds_filter_dest_cb(ds_set_t *node, int i, void *arg)
2657    {
2658            struct ds_filter_dest_cb_arg *filter_arg = (typeof(filter_arg)) arg;
2659
2660            if(node->id == filter_arg->setid && node->dlist[i].uri.len == filter_arg->dest->uri.len &&
2661                    strncmp(node->dlist[i].uri.s, filter_arg->dest->uri.s, filter_arg->dest->uri.len) == 0)
2662                    return;
2663
2664            if(add_dest2list(node->id, node->dlist[i].uri, node->dlist[i].flags,


```

#### Log Messages

```
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: ctl [../../core/io_wait.h:375]: io_watch_add(): processing io_watch_add(0x7f9032d07340, 10, 3, 0x1cdac70) - fd_no=1
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: ctl [io_listener.c:442]: handle_new_connect(): handle_stream read: new connection (1) on /var/run/kamailio//kamailio_ctl
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: ctl [io_listener.c:498]: handle_stream_read(): bytes read: 50
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: <core> [core/resolve.c:1784]: str2ipbuf(): error - too many dots in [127.0.0.1.test]
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: <core> [core/dns_cache.c:534]: _dns_hash_find(): (127.0.0.1.test(14), 1), h=312
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: <core> [core/resolve.c:1784]: str2ipbuf(): error - too many dots in [127.0.0.1.test]
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: <core> [core/resolve.c:784]: get_record(): lookup(127.0.0.1.test, 1) failed
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: <core> [core/dns_cache.c:768]: dns_cache_mk_bad_entry(): (127.0.0.1.test, 1, 5, 1)
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: <core> [core/dns_cache.c:709]: dns_cache_add(): adding 127.0.0.1.test(14) 1 (flags=1) at 312
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: ERROR: dispatcher [dispatch.c:517]: pack_dest(): could not resolve 127.0.0.1.test (missing no-probing flag?!?)
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: <core> [core/dns_cache.c:534]: _dns_hash_find(): (gate.core.test.local(41), 1), h=977
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: dispatcher [dispatch.c:581]: add_dest2list(): dest [2/1] <sip:gate.core.test.local:5080>
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: <core> [core/dns_cache.c:534]: _dns_hash_find(): (asterisk-626a9082134bb82ce844e99a-1.asterisk-626a9082134bb82ce844e99a.core.test.local(104), 1), h=127
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: dispatcher [dispatch.c:581]: add_dest2list(): dest [121/1] <sip:asterisk-626a9082134bb82ce844e99a-1.asterisk-626a9082134bb82ce844e99a.core.test.local:11000>
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: <core> [core/dns_cache.c:534]: _dns_hash_find(): (asterisk-626a9082134bb82ce844e99a-0.asterisk-626a9082134bb82ce844e99a.core.test.local(104), 1), h=126
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: dispatcher [dispatch.c:581]: add_dest2list(): dest [121/2] <sip:asterisk-626a9082134bb82ce844e99a-0.asterisk-626a9082134bb82ce844e99a.core.test.local:11000>
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: dispatcher [dispatch.c:581]: add_dest2list(): dest [16/1] <sip:10.1.144.125:1100>
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: <core> [core/dns_cache.c:534]: _dns_hash_find(): (asterisk-623478edd337ae4eb75e4592-1.asterisk-623478edd337ae4eb75e4592.core.test.local(104), 1), h=395
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: dispatcher [dispatch.c:581]: add_dest2list(): dest [134/1] <sip:asterisk-623478edd337ae4eb75e4592-1.asterisk-623478edd337ae4eb75e4592.core.test.local:11000>
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: <core> [core/dns_cache.c:534]: _dns_hash_find(): (asterisk-623478edd337ae4eb75e4592-0.asterisk-623478edd337ae4eb75e4592.core.test.local(104), 1), h=394
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: dispatcher [dispatch.c:581]: add_dest2list(): dest [134/2] <sip:asterisk-623478edd337ae4eb75e4592-0.asterisk-623478edd337ae4eb75e4592.core.test.local:11000>
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: <core> [core/dns_cache.c:534]: _dns_hash_find(): (asterisk-62cbe764f1967d2acee73137-1.asterisk-62cbe764f1967d2acee73137.core.test.local(104), 1), h=950
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: dispatcher [dispatch.c:581]: add_dest2list(): dest [142/1] <sip:asterisk-62cbe764f1967d2acee73137-1.asterisk-62cbe764f1967d2acee73137.core.test.local:11000>
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: <core> [core/dns_cache.c:534]: _dns_hash_find(): (asterisk-62cbe764f1967d2acee73137-0.asterisk-62cbe764f1967d2acee73137.core.test.local(104), 1), h=949
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: dispatcher [dispatch.c:581]: add_dest2list(): dest [142/2] <sip:asterisk-62cbe764f1967d2acee73137-0.asterisk-62cbe764f1967d2acee73137.core.test.local:11000>
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: <core> [core/dns_cache.c:534]: _dns_hash_find(): (asterisk-62863d882418f0548acb8878-1.asterisk-62863d882418f0548acb8878.core.test.local(104), 1), h=291
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: dispatcher [dispatch.c:581]: add_dest2list(): dest [135/1] <sip:asterisk-62863d882418f0548acb8878-1.asterisk-62863d882418f0548acb8878.core.test.local:11000>
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: <core> [core/dns_cache.c:534]: _dns_hash_find(): (asterisk-62863d882418f0548acb8878-0.asterisk-62863d882418f0548acb8878.core.test.local(104), 1), h=290
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: dispatcher [dispatch.c:581]: add_dest2list(): dest [135/2] <sip:asterisk-62863d882418f0548acb8878-0.asterisk-62863d882418f0548acb8878.core.test.local:11000>
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: <core> [core/dns_cache.c:534]: _dns_hash_find(): (asterisk-62de8c25cb42803beeb73dbe-1.asterisk-62de8c25cb42803beeb73dbe.core.test.local(104), 1), h=771
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: dispatcher [dispatch.c:581]: add_dest2list(): dest [144/1] <sip:asterisk-62de8c25cb42803beeb73dbe-1.asterisk-62de8c25cb42803beeb73dbe.core.test.local:11000>
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: <core> [core/dns_cache.c:534]: _dns_hash_find(): (asterisk-62de8c25cb42803beeb73dbe-0.asterisk-62de8c25cb42803beeb73dbe.core.test.local(104), 1), h=770
Jul 25 12:55:04 core /usr/sbin/kamailio[28880]: DEBUG: dispatcher [dispatch.c:581]: add_dest2list(): dest [144/2] <sip:asterisk-62de8c25cb42803beeb73dbe-0.asterisk-62de8c25cb42803beeb73dbe.core.test.local:11000>
Jul 25 12:55:04 core /usr/sbin/kamailio[28892]: CRITICAL: <core> [core/pass_fd.c:277]: receive_fd(): EOF on 5
Jul 25 12:55:04 core /usr/sbin/kamailio[28892]: DEBUG: <core> [core/tcp_main.c:3853]: handle_ser_child(): dead child 14, pid 28880 (shutting down?)
Jul 25 12:55:04 core /usr/sbin/kamailio[28892]: DEBUG: <core> [core/io_wait.h:600]: io_watch_del(): DBG: io_watch_del (0xafde80, 5, -1, 0x0) fd_no=37 called
Jul 25 12:55:04 core /usr/sbin/kamailio[28820]: ALERT: <core> [main.c:775]: handle_sigs(): child process 28880 exited by a signal 11
Jul 25 12:55:04 core /usr/sbin/kamailio[28820]: ALERT: <core> [main.c:778]: handle_sigs(): core was generated
Jul 25 12:55:04 core /usr/sbin/kamailio[28820]: INFO: <core> [main.c:799]: handle_sigs(): terminating due to SIGCHLD
Jul 25 12:55:04 core /usr/sbin/kamailio[28892]: INFO: <core> [main.c:854]: sig_usr(): signal 15 received
Jul 25 12:55:04 core /usr/sbin/kamailio[28820]: DEBUG: <core> [core/sr_module.c:832]: destroy_modules(): starting modules destroy phase
Jul 25 12:55:04 core /usr/sbin/kamailio[28820]: DEBUG: xhttp_prom [xhttp_prom.c:256]: mod_destroy(): cleaning up
Jul 25 12:55:04 core /usr/sbin/kamailio[28820]: DEBUG: xhttp_prom [prom_metric.c:243]: prom_metric_close(): Freeing lock
Jul 25 12:55:04 core /usr/sbin/kamailio[28820]: DEBUG: tm [t_funcs.c:84]: tm_shutdown(): start
Jul 25 12:55:04 core /usr/sbin/kamailio[28820]: DEBUG: tm [t_funcs.c:87]: tm_shutdown(): emptying hash table
Jul 25 12:55:04 core /usr/sbin/kamailio[28820]: DEBUG: tm [h_table.c:132]: free_cell_helper(): freeing transaction 0x7f90121d6b60 from h_table.c:466
Jul 25 12:55:04 core /usr/sbin/kamailio[28820]: DEBUG: tm [h_table.c:132]: free_cell_helper(): freeing transaction 0x7f9012201120 from h_table.c:466
Jul 25 12:55:04 core /usr/sbin/kamailio[28820]: DEBUG: tm [h_table.c:132]: free_cell_helper(): freeing transaction 0x7f90122034b0 from h_table.c:466
Jul 25 12:55:04 core /usr/sbin/kamailio[28820]: DEBUG: tm [h_table.c:132]: free_cell_helper(): freeing transaction 0x7f90121fca20 from h_table.c:466
Jul 25 12:55:04 core /usr/sbin/kamailio[28820]: DEBUG: tm [h_table.c:132]: free_cell_helper(): freeing transaction 0x7f90121fed90 from h_table.c:466
Jul 25 12:55:04 core /usr/sbin/kamailio[28820]: DEBUG: tm [t_funcs.c:89]: tm_shutdown(): removing semaphores
Jul 25 12:55:04 core /usr/sbin/kamailio[28820]: DEBUG: tm [t_funcs.c:91]: tm_shutdown(): destroying tmcb lists
Jul 25 12:55:04 core /usr/sbin/kamailio[28820]: DEBUG: tm [t_funcs.c:94]: tm_shutdown(): done
Jul 25 12:55:04 core /usr/sbin/kamailio[28820]: INFO: <core> [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized
Jul 25 12:55:04 core /usr/sbin/kamailio[28820]: DEBUG: <core> [core/mem/shm.c:290]: shm_destroy_manager(): destroying memory manager: q_malloc
Jul 25 12:55:04 core /usr/sbin/kamailio[28820]: DEBUG: <core> [core/mem/q_malloc.c:1260]: qm_shm_lock_destroy(): destroying the shared memory lock
Jul 25 12:55:04 core /usr/sbin/kamailio[28820]: DEBUG: <core> [core/mem/pkg.c:99]: pkg_destroy_manager(): destroying memory manager: q_malloc
Jul 25 12:55:04 core systemd[1]: kamailio.service: main process exited, code=exited, status=1/FAILURE
Jul 25 12:55:04 core systemd[1]: Unit kamailio.service entered failed state.
Jul 25 12:55:04 core systemd[1]: kamailio.service failed.
Jul 25 12:55:05 core systemd[1]: kamailio.service holdoff time over, scheduling restart.
Jul 25 12:55:05 core systemd[1]: Stopped Kamailio - the Open Source SIP Server.
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.6.0 (x86_64/linux) b0d6a6
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: b0d6a6
compiled on 13:24:32 May 30 2022 with gcc 4.8.5

```

* **Operating System**:

```
CentOS Linux release 7.9.2009 (Core)
```

**Comment by miconda** [comment]
Pushed a patch for it, referenced above. It will be backported. If still an issuem reopen.
