### ISSUE TITLE
 kamailio 5.7.0 development version can't use siprepo function sr_msg_push()

### ISSUE THREAD

**Issue by buzhaodi** [kamailio/kamailio#3418]
### Description

When I use the siprepo module, according to the documentation, I use the sr_msg_push function, and the startup log will report an error "failed to find command sr_msg_push (params 2)"
this is my cfg code:

            $var(msgid) = $sruid;
            if(sr_msg_push("$var(msgid)")) {
                xlog("L_INFO","OUT Call $ci: INVITE_PBX save the call mgsid is  $var(msgid),callid is $ci\n");
                exit();
            }

According to the code, I found that the parameters of this function should be two, and the second one is an int, but I did not find the use of the int type "rmode" in the siprepo_msg_set function。
So I changed the code to this：

           $var(msgid) = $sruid;
            if(sr_msg_push("$var(msgid)",1)) {
                xlog("L_INFO","OUT Call $ci: INVITE_PBX save the call mgsid is  $var(msgid),callid is $ci\n");
                exit();
            }

This time it started successfully, but a crash occurred when calling。The following is the core file analysis

#### Debugging Data

```
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from proxy...done.
[New LWP 78415]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Core was generated by `/proxy -P /proxy.pid -f /home'.
Program terminated with signal 11, Segmentation fault.
#0  0x00002b2a919420ae in get_hash1_raw (s=0x0, len=36) at ../../core/hashes.h:109
109		hash_update_str(s, s+len, p, v, h);
Missing separate debuginfos, use: debuginfo-install glibc-2.17-325.el7_9.x86_64 libcom_err-1.42.9-19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libgcrypt-1.5.3-14.el7.x86_64 libgpg-error-1.12-3.el7.x86_64 libunistring-0.9.3-9.el7.x86_64 lua-5.1.4-15.el7.x86_64 openssl-libs-1.0.2k-26.el7_9.x86_64 pcre-8.32-17.el7.x86_64 sqlite-3.7.17-8.el7_7.1.x86_64
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) bt
#0  0x00002b2a919420ae in get_hash1_raw (s=0x0, len=36) at ../../core/hashes.h:109
#1  0x00002b2a91944eb3 in siprepo_msg_set (msg=0x2b2a8aa810d0, msgid=0x7ffca5cbd8c0, rmode=1) at siprepo_data.c:222
#2  0x00002b2a91949eda in ki_sr_msg_push (msg=0x2b2a8aa810d0, msgid=0x7ffca5cbd8c0, rmode=1) at siprepo_mod.c:156
#3  0x00002b2a9194a60e in w_sr_msg_push (msg=0x2b2a8aa810d0, pmsgid=0x2b2a8a487b08 "\220zH\212*+", prmode=0x2b2a8a487c30 "") at siprepo_mod.c:181
#4  0x0000000000465a8c in do_action (h=0x7ffca5cbe190, a=0x2b2a8a48bad8, msg=0x2b2a8aa810d0) at core/action.c:1088
#5  0x0000000000472d29 in run_actions (h=0x7ffca5cbe190, a=0x2b2a8a48bad8, msg=0x2b2a8aa810d0) at core/action.c:1581
#6  0x00000000004733a5 in run_actions_safe (h=0x7ffca5cbee10, a=0x2b2a8a48bad8, msg=0x2b2a8aa810d0) at core/action.c:1645
#7  0x00000000004396e6 in rval_get_int (h=0x7ffca5cbee10, msg=0x2b2a8aa810d0, i=0x7ffca5cbeabc, rv=0x2b2a8a48cb78, cache=0x0) at core/rvalue.c:915
#8  0x000000000043e217 in rval_expr_eval_int (h=0x7ffca5cbee10, msg=0x2b2a8aa810d0, res=0x7ffca5cbeabc, rve=0x2b2a8a48cb70) at core/rvalue.c:1913
#9  0x0000000000465457 in do_action (h=0x7ffca5cbee10, a=0x2b2a8a48d7c8, msg=0x2b2a8aa810d0) at core/action.c:1052
#10 0x0000000000472d29 in run_actions (h=0x7ffca5cbee10, a=0x2b2a8a480510, msg=0x2b2a8aa810d0) at core/action.c:1581
#11 0x000000000047346d in run_top_route (a=0x2b2a8a480510, msg=0x2b2a8aa810d0, c=0x0) at core/action.c:1666
#12 0x00000000005d7f61 in receive_msg (
    buf=0xabca80 <buf.7134> "INVITE sip:1005@192.168.10.60:55067 SIP/2.0\r\nVia: SIP/2.0/UDP 192.168.10.77:5080;rport;branch=z9hG4bKjDFXQjF8278rr\r\nMax-Forwards: 70\r\nFrom: \"\" <sip:0000000000@192.168.10.77>;tag=gQ6aBXpg5gcXF\r\nTo: <si"..., len=1532, 
    rcv_info=0x7ffca5cbf500) at core/receive.c:423
#13 0x00000000004ca6fb in udp_rcv_loop () at core/udp_server.c:543
#14 0x0000000000429d47 in main_loop () at main.c:1683
#15 0x0000000000433a96 in main (argc=9, argv=0x7ffca5cbfd88) at main.c:2856
(gdb) f 1
#1  0x00002b2a91944eb3 in siprepo_msg_set (msg=0x2b2a8aa810d0, msgid=0x7ffca5cbd8c0, rmode=1) at siprepo_data.c:222
warning: Source file is more recent than executable.
222		it->hid = get_hash1_raw(it->callid.s, it->callid.len);
(gdb) info local
hid = 2879241394
slotid = 178
dsize = 1928
vbr = 0x2b2a8a9c72b0
scallid = {s = 0xabcb6e <buf.7134+238> "e7f00e70-5866-123c-f09f-b827ebf8b6d3\r\nCSeq: 66349691 INVITE\r\nContact: <sip:mod_sofia@192.168.10.77:5080>\r\nUser-Agent: FreeSWITCH-mod_sofia/1.10.1-dev-25-a4c5802372~32bit\r\nAllow: INVITE, ACK, BYE, CANC"..., 
  len = 36}
it = 0x2b2a92864d90
__FUNCTION__ = "siprepo_msg_set"
(gdb) p it->callid
$1 = {s = 0x0, len = 36}
(gdb) p it->hid 
$2 = 0
(gdb) p *it
$3 = {hid = 0, mtype = 0, msgid = {s = 0x0, len = 0}, callid = {s = 0x0, len = 36}, ftag = {
    s = 0xabcb32 <buf.7134+178> "gQ6aBXpg5gcXF\r\nTo: <sip:1005@192.168.10.60:55067>\r\nCall-ID: e7f00e70-5866-123c-f09f-b827ebf8b6d3\r\nCSeq: 66349691 INVITE\r\nContact: <sip:mod_sofia@192.168.10.77:5080>\r\nUser-Agent: FreeSWITCH-mod_sofia/1"..., 
    len = 13}, cseqnum = {
    s = 0xabcb9a <buf.7134+282> "66349691 INVITE\r\nContact: <sip:mod_sofia@192.168.10.77:5080>\r\nUser-Agent: FreeSWITCH-mod_sofia/1.10.1-dev-25-a4c5802372~32bit\r\nAllow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER"..., len = 8}, 
  cseqmet = {s = 0xabcba3 <buf.7134+291> "INVITE\r\nContact: <sip:mod_sofia@192.168.10.77:5080>\r\nUser-Agent: FreeSWITCH-mod_sofia/1.10.1-dev-25-a4c5802372~32bit\r\nAllow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, "..., 
    len = 6}, vbranch = {
    s = 0xabcade <buf.7134+94> "z9hG4bKjDFXQjF8278rr\r\nMax-Forwards: 70\r\nFrom: \"\" <sip:0000000000@192.168.10.77>;tag=gQ6aBXpg5gcXF\r\nTo: <sip:1005@192.168.10.60:55067>\r\nCall-ID: e7f00e70-5866-123c-f09f-b827ebf8b6d3\r\nCSeq: 66349691 INV"..., 
    len = 20}, dbuf = {s = 0x2b2a92864f00 "", len = 0}, cseqmetid = 0, msgno = 0, pid = 0, mflags = 0, rcv = {src_ip = {af = 0, len = 0, u = {addrl = {0, 0}, addr32 = {0, 0, 0, 0}, addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, addr = '\000' <repeats 15 times>}}, 
    dst_ip = {af = 0, len = 0, u = {addrl = {0, 0}, addr32 = {0, 0, 0, 0}, addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, addr = '\000' <repeats 15 times>}}, src_port = 0, dst_port = 0, proto_reserved1 = 0, proto_reserved2 = 0, src_su = {s = {sa_family = 0, 
        sa_data = '\000' <repeats 13 times>}, sin = {sin_family = 0, sin_port = 0, sin_addr = {s_addr = 0}, sin_zero = "\000\000\000\000\000\000\000"}, sin6 = {sin6_family = 0, sin6_port = 0, sin6_flowinfo = 0, sin6_addr = {__in6_u = {
            __u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, sin6_scope_id = 0}, sas = {ss_family = 0, __ss_padding = '\000' <repeats 117 times>, __ss_align = 0}}, bind_address = 0x0, 
    proto = 0 '\000', proto_pad0 = 0 '\000', proto_pad1 = 0}, itime = 0, next = 0x0, prev = 0x0}
(gdb) p * msg
$4 = {id = 1, pid = 0, tval = {tv_sec = 0, tv_usec = 0}, fwd_send_flags = {f = 0, blst_imask = 0}, rpl_send_flags = {f = 0, blst_imask = 0}, first_line = {type = 1, flags = 1, len = 45, u = {request = {method = {
          s = 0xabca80 <buf.7134> "INVITE sip:1005@192.168.10.60:55067 SIP/2.0\r\nVia: SIP/2.0/UDP 192.168.10.77:5080;rport;branch=z9hG4bKjDFXQjF8278rr\r\nMax-Forwards: 70\r\nFrom: \"\" <sip:0000000000@192.168.10.77>;tag=gQ6aBXpg5gcXF\r\nTo: <si"..., 
          len = 6}, uri = {
          s = 0xabca87 <buf.7134+7> "sip:1005@192.168.10.60:55067 SIP/2.0\r\nVia: SIP/2.0/UDP 192.168.10.77:5080;rport;branch=z9hG4bKjDFXQjF8278rr\r\nMax-Forwards: 70\r\nFrom: \"\" <sip:0000000000@192.168.10.77>;tag=gQ6aBXpg5gcXF\r\nTo: <sip:1005@"..., 
          len = 28}, version = {
          s = 0xabcaa4 <buf.7134+36> "SIP/2.0\r\nVia: SIP/2.0/UDP 192.168.10.77:5080;rport;branch=z9hG4bKjDFXQjF8278rr\r\nMax-Forwards: 70\r\nFrom: \"\" <sip:0000000000@192.168.10.77>;tag=gQ6aBXpg5gcXF\r\nTo: <sip:1005@192.168.10.60:55067>\r\nCall-ID"..., 
          len = 7}, method_value = 1}, reply = {version = {
          s = 0xabca80 <buf.7134> "INVITE sip:1005@192.168.10.60:55067 SIP/2.0\r\nVia: SIP/2.0/UDP 192.168.10.77:5080;rport;branch=z9hG4bKjDFXQjF8278rr\r\nMax-Forwards: 70\r\nFrom: \"\" <sip:0000000000@192.168.10.77>;tag=gQ6aBXpg5gcXF\r\nTo: <si"..., 
          len = 6}, status = {
          s = 0xabca87 <buf.7134+7> "sip:1005@192.168.10.60:55067 SIP/2.0\r\nVia: SIP/2.0/UDP 192.168.10.77:5080;rport;branch=z9hG4bKjDFXQjF8278rr\r\nMax-Forwards: 70\r\nFrom: \"\" <sip:0000000000@192.168.10.77>;tag=gQ6aBXpg5gcXF\r\nTo: <sip:1005@"..., 
          len = 28}, reason = {
          s = 0xabcaa4 <buf.7134+36> "SIP/2.0\r\nVia: SIP/2.0/UDP 192.168.10.77:5080;rport;branch=z9hG4bKjDFXQjF8278rr\r\nMax-Forwards: 70\r\nFrom: \"\" <sip:0000000000@192.168.10.77>;tag=gQ6aBXpg5gcXF\r\nTo: <sip:1005@192.168.10.60:55067>\r\nCall-ID"..., 
          len = 7}, statuscode = 1}}}, via1 = 0x2b2a8a9c70b8, via2 = 0x0, headers = 0x2b2a8a9c7010, last_header = 0x2b2a8a9b5a50, parsed_flag = 18446744073709551615, h_via1 = 0x2b2a8a9c7010, h_via2 = 0x0, callid = 0x2b2a8a9b2068, to = 0x2b2a8a9adaa8, 
  cseq = 0x2b2a8a9b2110, from = 0x2b2a8a9ad728, contact = 0x2b2a8a9b2250, maxforwards = 0x2b2a8a9ad680, route = 0x0, record_route = 0x0, content_type = 0x2b2a8a9b2598, content_length = 0x2b2a8a9b26e8, authorization = 0x0, expires = 0x0, proxy_auth = 0x0, 
  supported = 0x2b2a8a9b2448, require = 0x0, proxy_require = 0x0, unsupported = 0x0, allow = 0x2b2a8a9b23a0, event = 0x0, accept = 0x0, accept_language = 0x0, organization = 0x0, priority = 0x0, subject = 0x0, user_agent = 0x2b2a8a9b22f8, server = 0x0, 
  content_disposition = 0x2b2a8a9b2640, diversion = 0x0, rpid = 0x2b2a8a9b5a50, refer_to = 0x0, session_expires = 0x0, min_se = 0x0, sipifmatch = 0x0, subscription_state = 0x0, date = 0x0, identity = 0x0, identity_info = 0x0, pai = 0x0, ppi = 0x0, 
  path = 0x0, privacy = 0x0, min_expires = 0x0, body = 0x0, 
  eoh = 0xabcd92 <buf.7134+786> "\r\nv=0\r\no=FreeSWITCH 1681788467 1681788468 IN IP4 192.168.10.77\r\ns=FreeSWITCH\r\nc=IN IP4 192.168.10.77\r\nt=0 0\r\nm=audio 18500 RTP/AVP 102 9 0 8 105 101\r\na=rtpmap:102 opus/48000/2\r\na=fmtp:102 useinbandfec"..., 
  unparsed = 0xabcd92 <buf.7134+786> "\r\nv=0\r\no=FreeSWITCH 1681788467 1681788468 IN IP4 192.168.10.77\r\ns=FreeSWITCH\r\nc=IN IP4 192.168.10.77\r\nt=0 0\r\nm=audio 18500 RTP/AVP 102 9 0 8 105 101\r\na=rtpmap:102 opus/48000/2\r\na=fmtp:102 useinbandfec"..., rcv = {src_ip = {af = 2, len = 4, u = {addrl = {1292544192, 0}, addr32 = {1292544192, 0, 0, 0}, addr16 = {43200, 19722, 0, 0, 0, 0, 0, 0}, addr = "\300\250\nM", '\000' <repeats 11 times>}}, dst_ip = {af = 2, len = 4, u = {addrl = {1007331520, 0}, 
        addr32 = {1007331520, 0, 0, 0}, addr16 = {43200, 15370, 0, 0, 0, 0, 0, 0}, addr = "\300\250\n<", '\000' <repeats 11 times>}}, src_port = 5080, dst_port = 55067, proto_reserved1 = 0, proto_reserved2 = 0, src_su = {s = {sa_family = 2, 
        sa_data = "\023\330\300\250\nM\000\000\000\000\000\000\000"}, sin = {sin_family = 2, sin_port = 55315, sin_addr = {s_addr = 1292544192}, sin_zero = "\000\000\000\000\000\000\000"}, sin6 = {sin6_family = 2, sin6_port = 55315, 
        sin6_flowinfo = 1292544192, sin6_addr = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, sin6_scope_id = 0}, sas = {ss_family = 2, 
        __ss_padding = "\023\330\300\250\nM", '\000' <repeats 111 times>, __ss_align = 0}}, bind_address = 0x2b2a8a47c2d0, proto = 1 '\001', proto_pad0 = 0 '\000', proto_pad1 = 0}, 
  buf = 0xabca80 <buf.7134> "INVITE sip:1005@192.168.10.60:55067 SIP/2.0\r\nVia: SIP/2.0/UDP 192.168.10.77:5080;rport;branch=z9hG4bKjDFXQjF8278rr\r\nMax-Forwards: 70\r\nFrom: \"\" <sip:0000000000@192.168.10.77>;tag=gQ6aBXpg5gcXF\r\nTo: <si"..., len = 1532, 
  new_uri = {s = 0x0, len = 0}, dst_uri = {s = 0x0, len = 0}, parsed_uri_ok = 1, parsed_uri = {user = {
      s = 0xabca8b <buf.7134+11> "1005@192.168.10.60:55067 SIP/2.0\r\nVia: SIP/2.0/UDP 192.168.10.77:5080;rport;branch=z9hG4bKjDFXQjF8278rr\r\nMax-Forwards: 70\r\nFrom: \"\" <sip:0000000000@192.168.10.77>;tag=gQ6aBXpg5gcXF\r\nTo: <sip:1005@192."..., 
      len = 4}, passwd = {s = 0x0, len = 0}, host = {
      s = 0xabca90 <buf.7134+16> "192.168.10.60:55067 SIP/2.0\r\nVia: SIP/2.0/UDP 192.168.10.77:5080;rport;branch=z9hG4bKjDFXQjF8278rr\r\nMax-Forwards: 70\r\nFrom: \"\" <sip:0000000000@192.168.10.77>;tag=gQ6aBXpg5gcXF\r\nTo: <sip:1005@192.168.1"..., 
      len = 13}, port = {
---Type <return> to continue, or q <return> to quit---
      s = 0xabca9e <buf.7134+30> "55067 SIP/2.0\r\nVia: SIP/2.0/UDP 192.168.10.77:5080;rport;branch=z9hG4bKjDFXQjF8278rr\r\nMax-Forwards: 70\r\nFrom: \"\" <sip:0000000000@192.168.10.77>;tag=gQ6aBXpg5gcXF\r\nTo: <sip:1005@192.168.10.60:55067>\r\nC"..., 
      len = 5}, params = {s = 0x0, len = 0}, sip_params = {s = 0x0, len = 0}, headers = {s = 0x0, len = 0}, port_no = 55067, proto = 0, type = SIP_URI_T, flags = (unknown: 0), transport = {s = 0x0, len = 0}, ttl = {s = 0x0, len = 0}, user_param = {s = 0x0, 
      len = 0}, maddr = {s = 0x0, len = 0}, method = {s = 0x0, len = 0}, lr = {s = 0x0, len = 0}, r2 = {s = 0x0, len = 0}, gr = {s = 0x0, len = 0}, transport_val = {s = 0x0, len = 0}, ttl_val = {s = 0x0, len = 0}, user_param_val = {s = 0x0, len = 0}, 
    maddr_val = {s = 0x0, len = 0}, method_val = {s = 0x0, len = 0}, lr_val = {s = 0x0, len = 0}, r2_val = {s = 0x0, len = 0}, gr_val = {s = 0x0, len = 0}}, parsed_orig_ruri_ok = 0, parsed_orig_ruri = {user = {s = 0x0, len = 0}, passwd = {s = 0x0, 
      len = 0}, host = {s = 0x0, len = 0}, port = {s = 0x0, len = 0}, params = {s = 0x0, len = 0}, sip_params = {s = 0x0, len = 0}, headers = {s = 0x0, len = 0}, port_no = 0, proto = 0, type = ERROR_URI_T, flags = (unknown: 0), transport = {s = 0x0, 
      len = 0}, ttl = {s = 0x0, len = 0}, user_param = {s = 0x0, len = 0}, maddr = {s = 0x0, len = 0}, method = {s = 0x0, len = 0}, lr = {s = 0x0, len = 0}, r2 = {s = 0x0, len = 0}, gr = {s = 0x0, len = 0}, transport_val = {s = 0x0, len = 0}, ttl_val = {
      s = 0x0, len = 0}, user_param_val = {s = 0x0, len = 0}, maddr_val = {s = 0x0, len = 0}, method_val = {s = 0x0, len = 0}, lr_val = {s = 0x0, len = 0}, r2_val = {s = 0x0, len = 0}, gr_val = {s = 0x0, len = 0}}, add_rm = 0x0, body_lumps = 0x0, 
  reply_lump = 0x0, add_to_branch_s = '\000' <repeats 57 times>, add_to_branch_len = 0, hash_index = 1864, msg_flags = 128, flags = 0, xflags = {0, 0}, set_global_address = {s = 0x0, len = 0}, set_global_port = {s = 0x0, len = 0}, force_send_socket = 0x0, 
  path_vec = {s = 0x0, len = 0}, instance = {s = 0x0, len = 0}, reg_id = 0, ruid = {s = 0x0, len = 0}, location_ua = {s = 0x0, len = 0}, otcpid = 0, ldv = {flow = {decoded = 0, rcv = {src_ip = {af = 0, len = 0, u = {addrl = {0, 0}, addr32 = {0, 0, 0, 0}, 
            addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, addr = '\000' <repeats 15 times>}}, dst_ip = {af = 0, len = 0, u = {addrl = {0, 0}, addr32 = {0, 0, 0, 0}, addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, addr = '\000' <repeats 15 times>}}, src_port = 0, dst_port = 0, 
        proto_reserved1 = 0, proto_reserved2 = 0, src_su = {s = {sa_family = 0, sa_data = '\000' <repeats 13 times>}, sin = {sin_family = 0, sin_port = 0, sin_addr = {s_addr = 0}, sin_zero = "\000\000\000\000\000\000\000"}, sin6 = {sin6_family = 0, 
            sin6_port = 0, sin6_flowinfo = 0, sin6_addr = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, sin6_scope_id = 0}, sas = {ss_family = 0, 
            __ss_padding = '\000' <repeats 117 times>, __ss_align = 0}}, bind_address = 0x0, proto = 0 '\000', proto_pad0 = 0 '\000', proto_pad1 = 0}}, vdata = 0x0}}
```

#### Log Messages

 segfault at 0 ip 00002b2a919420ae sp 00007ffca5cbd6a0 error 4 in siprepo.so[2b2a91940000+f000]

#### SIP Traffic
I just sent an invite via freeswitch：

```
INVITE` sip:1005@192.168.10.60:55067 SIP/2.0
Via: SIP/2.0/UDP 192.168.10.77:5080;rport;branch=z9hG4bKjDFXQjF8278rr
Max-Forwards: 70
From: "" <sip:0000000000@192.168.10.77>;tag=gQ6aBXpg5gcXF
To: <sip:1005@192.168.10.60:55067>
Call-ID: e7f00e70-5866-123c-f09f-b827ebf8b6d3
CSeq: 66349691 INVITE
Contact: <sip:mod_sofia@192.168.10.77:5080>
User-Agent: FreeSWITCH-mod_sofia/1.10.1-dev-25-a4c5802372~32bit
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY
Supported: timer, path, replaces
Allow-Events: talk, hold, conference, refer
Content-Type: application/sdp
Content-Disposition: session
Content-Length: 744
X-FS-Support: update_display,send_info
Remote-Party-ID: <sip:0000000000@192.168.10.77>;party=calling;screen=yes;privacy=off

v=0
o=FreeSWITCH 1681788467 1681788468 IN IP4 192.168.10.77
s=FreeSWITCH
c=IN IP4 192.168.10.77
t=0 0
m=audio 18500 RTP/AVP 102 9 0 8 105 101
a=rtpmap:102 opus/48000/2
a=fmtp:102 useinbandfec=1; maxaveragebitrate=30000; maxplaybackrate=48000; ptime=20; minptime=10; maxptime=40

```

* **Operating System**:
Linux siphostexternal 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux on centos7.9.2009

```
version: kamailio 5.7.0-pre0 (x86_64/linux) 77c41d
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, MEM_JOIN_FREE, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 77c41d 
compiled on 16:24:27 Apr 18 2023 with gcc 4.8.5
```

**Comment by miconda** [comment]
Can you try with development version (master branch)? I pushed a commit (referenced above) for this one.

**Comment by buzhaodi** [comment]
thanks for your commit,i try it.it's work.however,  when set _siprepo_table,it't crash,this  is gdb debug.
```
/corefile>gdb /home/ucp/ka/sbin/kamailio core-kamailio-100062-1681861889 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/ucp/ka/sbin/kamailio...done.
[New LWP 100062]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./kamailio -P /home/ucp/ka/kamailio.pid -f /home/ucp/ka/etc/kamailio//kamailio.'.
Program terminated with signal 11, Segmentation fault.
#0  0x00002b69dddb61a7 in siprepo_msg_set (msg=0x2b69da63d000, msgid=0x7fff491e8f70, rmode=1) at siprepo_data.c:245
245		_siprepo_table[slotid].plist->prev = it;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-325.el7_9.x86_64
(gdb) 
(gdb) 
(gdb) 
(gdb) bt
#0  0x00002b69dddb61a7 in siprepo_msg_set (msg=0x2b69da63d000, msgid=0x7fff491e8f70, rmode=1) at siprepo_data.c:245
#1  0x00002b69dddbb182 in ki_sr_msg_push (msg=0x2b69da63d000, msgid=0x7fff491e8f70, rmode=1) at siprepo_mod.c:156
#2  0x00002b69dddbb8b6 in w_sr_msg_push (msg=0x2b69da63d000, pmsgid=0x2b69da6080d0 "X\200`\332i+", 
    prmode=0x2b69da608268 "\370\201`\332i+") at siprepo_mod.c:181
#3  0x0000000000466069 in do_action (h=0x7fff491e9860, a=0x2b69da60cc38, msg=0x2b69da63d000) at core/action.c:1093
#4  0x0000000000473234 in run_actions (h=0x7fff491e9860, a=0x2b69da60cc38, msg=0x2b69da63d000) at core/action.c:1587
#5  0x00000000004738b0 in run_actions_safe (h=0x7fff491eb5d0, a=0x2b69da60cc38, msg=0x2b69da63d000) at core/action.c:1651
#6  0x00000000006ccf5f in rval_get_long (h=0x7fff491eb5d0, msg=0x2b69da63d000, i=0x7fff491ea188, rv=0x2b69da60dd50, cache=0x0)
    at core/rvalue.c:955
#7  0x00000000006d1b2d in rval_expr_eval_long (h=0x7fff491eb5d0, msg=0x2b69da63d000, res=0x7fff491ea188, rve=0x2b69da60dd48)
    at core/rvalue.c:1855
#8  0x0000000000465a36 in do_action (h=0x7fff491eb5d0, a=0x2b69da60ea88, msg=0x2b69da63d000) at core/action.c:1057
#9  0x0000000000473234 in run_actions (h=0x7fff491eb5d0, a=0x2b69da60ca00, msg=0x2b69da63d000) at core/action.c:1587
#10 0x0000000000465edd in do_action (h=0x7fff491eb5d0, a=0x2b69da613308, msg=0x2b69da63d000) at core/action.c:1072
#11 0x0000000000473234 in run_actions (h=0x7fff491eb5d0, a=0x2b69da60ab30, msg=0x2b69da63d000) at core/action.c:1587
#12 0x00000000004626eb in do_action (h=0x7fff491eb5d0, a=0x2b69da5ea678, msg=0x2b69da63d000) at core/action.c:705
#13 0x0000000000473234 in run_actions (h=0x7fff491eb5d0, a=0x2b69da5e14d0, msg=0x2b69da63d000) at core/action.c:1587
#14 0x0000000000473978 in run_top_route (a=0x2b69da5e14d0, msg=0x2b69da63d000, c=0x0) at core/action.c:1672
#15 0x00000000005d1e0a in receive_msg (
    buf=0xb070e0 <buf.7262> "INVITE sip:1005@192.168.10.60:50666 SIP/2.0\r\nVia: SIP/2.0/UDP 192.168.10.77:5080;rport;branch=z9hG4bK7a25vaHj62v1B\r\nMax-Forwards: 69\r\nFrom: \"\" <sip:0000000000@192.168.10.77>;tag=pe7re1ppQ3t3Q\r\nTo: <si"..., len=1532, 
    rcv_info=0x7fff491ebce0) at core/receive.c:515
#16 0x00000000004ad697 in udp_rcv_loop () at core/udp_server.c:587
#17 0x000000000042a4ee in main_loop () at main.c:1510
#18 0x0000000000437c75 in main (argc=5, argv=0x7fff491ec5b8) at main.c:3086
(gdb) f 0
#0  0x00002b69dddb61a7 in siprepo_msg_set (msg=0x2b69da63d000, msgid=0x7fff491e8f70, rmode=1) at siprepo_data.c:245
245		_siprepo_table[slotid].plist->prev = it;
(gdb) info local
hid = 1910957457
slotid = 145
dsize = 1928
vbr = 0x2b69da620738
scallid = {
  s = 0xb071ce <buf.7262+238> "5131603a-5924-123c-f09f-b827ebf8b6d3\r\nCSeq: 66390367 INVITE\r\nContact: <sip:mod_sofia@192.168.10.77:5080>\r\nUser-Agent: FreeSWITCH-mod_sofia/1.10.1-dev-25-a4c5802372~32bit\r\nAllow: INVITE, ACK, BYE, CANC"..., len = 36}
it = 0x2b69de2697d0
__FUNCTION__ = "siprepo_msg_set"
(gdb) p slotid
$1 = 145
(gdb) p _siprepo_table[145]
$2 = {plist = 0x0, lock = {val = 1}}
(gdb) 
```

**Comment by miconda** [comment]
Reopen if the above commit didn't fix it.
