### ISSUE TITLE
kamcmd.c: memory leak

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#3478]
```
==70169==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4096 byte(s) in 15 object(s) allocated from:
    #0 0xffffaed756eb in malloc (/lib64/libasan.so.5+0xd56eb)
    #1 0x4137e7 in get_cfgvars_list /usr/src/debug/kamailio-5.6.4-4.el8.centos.aarch64/utils/kamcmd/kamcmd.c:1353
    #2 0x41ea03 in main (/usr/sbin/kamcmd+0x41ea03)
    #3 0xffffade04383 in __libc_start_main (/lib64/libc.so.6+0x24383)
    #4 0x402cbb  (/usr/sbin/kamcmd+0x402cbb)

SUMMARY: AddressSanitizer: 4096 byte(s) leaked in 15 allocation(s).
```

Link to source code
https://github.com/kamailio/kamailio/blob/5.6.4/utils/kamcmd/kamcmd.c#L1353

**Comment by henningw** [comment]
Thanks for the report, will have a look

**Comment by henningw** [comment]
@pantelisk98
