### ISSUE TITLE
Python exception handling

### ISSUE THREAD

**Issue by smurfix** [kamailio/kamailio#4045]
### Description

The Python3 modules violate Python's exception handling contract.

#### Reproduction

```
KSR.pc.sets("$fU",None)
```

#### Debugging Data

```
Unhandled exception in the Python code:
TypeError: kemi-param-ss() argument 2 must be str, not None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/kamailio/trace.py", line 212, in pac
    return proc(*a, **k)
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/kamailio/_basic.py", line 181, in ksr_request_route
    self.do_route(msg)
  File "/usr/local/lib/python3.11/dist-packages/kamailio/_basic.py", line 261, in do_route
    self.route_static(msg)
  File "/usr/local/lib/python3.11/dist-packages/kamailio/_basic.py", line 287, in route_static
    if self.fix_addrs(msg):
       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/kamailio/_basic.py", line 334, in fix_addrs
    PV.tU = dnr
    ^^^^^
  File "/usr/local/lib/python3.11/dist-packages/kamailio/var.py", line 46, in __setattr__
    return self.__setitem__(k, v)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/kamailio/var.py", line 73, in __setitem__
    KSR.pv.sets("$fU", v)
SystemError: <built-in function sets> returned a result with an exception set
```

### Possible Solutions

See PR #4044

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
seen with 5.6 and 5.8
```

* **Operating System**:

Debian Stable but doesn't matter

**Comment by miconda** [comment]
The second parameter for KSR.pv.sets(...)  must be a valid string. If you want to unset a pv, use KSR.ov.unset(...). For discussing further about using or configuring kamailio, use sr-users@lists.kamailio.org mailing list.

**Comment by smurfix** [comment]
Yes. I *know* that it must be a valid string. The problem is what happens if it is not. The Python exception that's raised in this case is accomoanied by your C code not returning NULL, and that's simply wrong according to the Python C interface documentation.
