### ISSUE TITLE
Crash with corex send() since 027495fb (4.3.3 -> 4.3.4)

### ISSUE THREAD

**Issue by pwarnold** [kamailio/kamailio#496]
Since upgrading from 4.3.3 to 4.3.4 I'm seeing a crash when calling send() from the corex module. The backtrace is included below.

It looks like the problem was introduced in 027495fb (cherry picked into 4.3: 4fdd1169, 4.2: 5b93cc21 and 4.1: 8e010d9f).

I can confirm that 4.3.4 with 4fdd1169 reverted doesn't crash.
```
#0  memchr () at ../sysdeps/x86_64/memchr.S:33
33      ../sysdeps/x86_64/memchr.S: No such file or directory.
(gdb) bt
#0  memchr () at ../sysdeps/x86_64/memchr.S:33
#1  0x00007f477b6eb50d in corex_send (msg=0x7f4780940508, pu=<optimized out>, proto=proto@entry=PROTO_UDP) at corex_lib.c:265
#2  0x00007f477b6edf3e in w_send (msg=<optimized out>, su=<optimized out>, sq=<optimized out>) at corex_mod.c:174
#3  0x0000000000429127 in do_action (h=h@entry=0x7ffe874baf10, a=a@entry=0x7f47808553c8, msg=msg@entry=0x7f4780940508) at action.c:1059
#4  0x0000000000427dc9 in run_actions (h=h@entry=0x7ffe874baf10, a=0x7f47808553c8, msg=msg@entry=0x7f4780940508) at action.c:1548
#5  0x00000000004297fc in do_action (h=h@entry=0x7ffe874baf10, a=a@entry=0x7f4780855ed8, msg=msg@entry=0x7f4780940508) at action.c:1048
#6  0x0000000000427dc9 in run_actions (h=h@entry=0x7ffe874baf10, a=0x7f4780855ed8, msg=msg@entry=0x7f4780940508) at action.c:1548
#7  0x00000000004297fc in do_action (h=h@entry=0x7ffe874baf10, a=a@entry=0x7f4780856020, msg=msg@entry=0x7f4780940508) at action.c:1048
#8  0x0000000000427dc9 in run_actions (h=h@entry=0x7ffe874baf10, a=0x7f4780856020, msg=msg@entry=0x7f4780940508) at action.c:1548
#9  0x00000000004297fc in do_action (h=h@entry=0x7ffe874baf10, a=a@entry=0x7f4780856248, msg=msg@entry=0x7f4780940508) at action.c:1048
#10 0x0000000000427dc9 in run_actions (h=h@entry=0x7ffe874baf10, a=0x7f478084bdb0, msg=msg@entry=0x7f4780940508) at action.c:1548
#11 0x00000000004298e5 in do_action (h=h@entry=0x7ffe874baf10, a=a@entry=0x7f47808075e0, msg=msg@entry=0x7f4780940508) at action.c:677
#12 0x0000000000427dc9 in run_actions (h=h@entry=0x7ffe874baf10, a=a@entry=0x7f47808005f0, msg=msg@entry=0x7f4780940508) at action.c:1548
#13 0x0000000000434610 in run_top_route (a=0x7f47808005f0, msg=msg@entry=0x7f4780940508, c=c@entry=0x0) at action.c:1634
#14 0x00000000004f768e in receive_msg (buf=<optimized out>, len=<optimized out>, rcv_info=<optimized out>) at receive.c:196
#15 0x00000000005dee7d in udp_rcv_loop () at udp_server.c:495
#16 0x00000000004a8a43 in main_loop () at main.c:1577
#17 0x00000000004272e7 in main (argc=<optimized out>, argv=<optimized out>) at main.c:2553
```

**Comment by miconda** [comment]
Ohh, regression introduced indeed. Thanks for the report. I pushed a patch that hopefully fix it. Can you try with latest branch 4.3 and report the results?

**Comment by linuxmaniac** [comment]
@pwarnold please use markdown format when pasting gdb output. github gets confused :-(

**Comment by pwarnold** [comment]
I can confirm no crash with the latest 4.3 branch. Thanks for the fix.
